"use strict";

module.exports = {
  app: {
    // Frontend → E2E handoff. Keep the selector contract in this one place.
    readyTestId: "app-shell",
    loaderTestId: "app-loading",
    errorTestId: "app-error",
    pageUrlMatch: "/user/apps/signal_analyser",
    supportsStaleReplay: true,
    testIds: {
      shell: "app-shell",
      displayTabs: "display-tabs",
      addDisplay: "add-display",
      displayOverflowTrigger: "display-overflow-trigger",
      displayOverflowMenu: "display-overflow-menu",
      clearDisplayAction: "clear-display-action",
      emptyDisplay: {
        plot: "empty-display-plot-state",
        measurements: "empty-display-measurements-state",
        peaks: "empty-display-peaks-state",
      },
      displayCanvas: "display-canvas",
      displayPlotTitle: "display-plot-title",
      activePlotHost: "active-plot-host",
      plotErrorState: "plot-error-state",
      plotInvalidDataState: "plot-invalid-data-state",
      findPeaksAction: "find-peaks-action",
      signalStatisticsAction: "signal-statistics-action",
      normalizeYAxisCheckbox: "normalize-y-checkbox",
      showMarkersCheckbox: "show-markers-checkbox",
      timeMinInput: "time-min-input",
      timeMaxInput: "time-max-input",
      timeLimitsError: "time-limits-error",
      statisticsSettingsTab: "statistics-settings-tab",
      statisticsControls: "statistics-controls",
      statisticsOptionPrefix: "statistics-option-",
      statisticsSelectionError: "statistics-selection-error",
      spectrumSettings: "spectrum-settings",
      spectrumScaleSelect: "spectrum-scale-select",
      spectrumFrequencyScaleSelect: "spectrum-frequency-scale-select",
      spectrumLeakageInput: "spectrum-leakage-input",
      spectrumSettingsError: "spectrum-settings-error",
      spectrumFrequencyMinInput: "spectrum-frequency-min-input",
      spectrumFrequencyMaxInput: "spectrum-frequency-max-input",
      spectrumFrequencyLimitsError: "spectrum-frequency-limits-error",
      spectrogramSettings: "spectrogram-settings",
      spectrogramOverlapPercentInput: "spectrogram-overlap-percent-input",
      spectrogramOverlapPercentError: "spectrogram-overlap-percent-error",
      spectrogramLeakageInput: "spectrogram-leakage-input",
      spectrogramLeakageError: "spectrogram-leakage-error",
      spectrogramFrequencyMinInput: "spectrogram-frequency-min-input",
      spectrogramFrequencyMaxInput: "spectrogram-frequency-max-input",
      spectrogramFrequencyLimitsError: "spectrogram-frequency-limits-error",
      spectrogramFrequencyScaleSelect: "spectrogram-frequency-scale-select",
      spectrogramFrequencyScaleEffective: "spectrogram-frequency-scale-effective",
      spectrogramFrequencyScaleError: "spectrogram-frequency-scale-error",
      spectrogramPowerLimitsControls: "spectrogram-power-limits-controls",
      spectrogramPowerMinInput: "spectrogram-power-min-input",
      spectrogramPowerMaxInput: "spectrogram-power-max-input",
      spectrogramPowerLimitsEffective: "spectrogram-power-limits-effective",
      spectrogramPowerLimitsError: "spectrogram-power-limits-error",
      persistenceSettings: "persistence-settings",
      persistenceLeakageInput: "persistence-leakage-input",
      persistenceLeakageValue: "persistence-leakage-value",
      persistenceLeakageError: "persistence-leakage-error",
      plotTypeSelect: "plot-type-select",
      settingsViewSelect: "settings-view-select",
      toggleAllSignals: "toggle-all-signals",
      plotGrid: "plot-grid",
      plotCards: {
        time: "plot-card-time",
        spectrum: "plot-card-spectrum",
        spectrogram: "plot-card-spectrogram",
        persistence: "plot-card-persistence",
      },
      plotTitles: {
        time: "Время",
        spectrum: "Спектр",
        spectrogram: "Спектрограмма",
        persistence: "Спектр персистентности",
      },
      activePlotPanel: "active-plot-panel",
      activePlotTitle: "active-plot-title",
      signalTable: "signal-table",
      signalRowPrefix: "signal-row-",
      signalVisibilityCheckboxPrefix: "signal-checkbox-",
      signalVisibilityStatePrefix: "signal-visibility-state-",
      activePlotFieldPrefix: "active-plot-field-",
      // Kept only so disabled legacy four-card specs still load for syntax.
      // Current DEC-009 runtime uses activePlotHost exclusively.
      plotHostPrefix: "plot-host-",
      measurements: {
        signalsTab: "signal-panel-tab-signals",
        measurementsTab: "signal-panel-tab-measurements",
        panel: "measurements-panel",
        signalName: "measurements-signal-name",
        table: "measurements-table",
        rows: {
          minimum: "measurement-row-minimum",
          maximum: "measurement-row-maximum",
          mean: "measurement-row-mean",
        },
      },
      peaks: {
        tab: "peaks-panel-tab",
        panel: "peaks-panel",
        signalName: "peaks-signal-name",
        table: "peaks-table",
        loading: "peaks-loading-state",
        error: "peaks-error-state",
        empty: "peaks-empty-state",
        rowPrefix: "peak-row-",
      },
    },
    api: {
      state: "/api/state",
      view: "/api/view",
      displays: "/api/displays",
    },
    // Signal rows are buttons; selection is their native pressed state.
    selectedState: ["aria-pressed"],
    // The active plot card exposes pressed state and the application styling class.
    activeClass: "is-active",
    activeState: ["aria-pressed"],
  },
  features: {
    "layout-geometry": true,
    "style-system": false,
    "frontend-state-management": true,
    "settings-controls": false,
    // Cascade 3 P0: authoritative state snapshots expose selected-visible raw
    // statistics; the bottom-tab switch itself remains entirely local.
    "measurements-statistics": true,
    "peaks": true,
    "clear-display": true,
    "time-presentation": true,
    "time-limits": true,
    "selectable-statistics": true,
    "spectrum-settings-roi": true,
    "frequency-limits": true,
    "typed-spectrogram": true,
    "typed-persistence": true,
    "persistence-leakage": true,
    // DEC-029 / Cascade 23 is a planned runtime contract.  Keep its E2E
    // scenario parseable and explicitly gated until its target is available.
    "lazy-persistence-materialization": false,
    // DEC-032 / Cascade 26 remains a target-gated browser contract.  Its
    // scenario routes only /api/state and is disabled until the fatal/Retry
    // behavior is available in the selected frontend target.
    "global-snapshot-envelope": false,
    "spectrogram-overlap": true,
    "spectrogram-leakage": true,
    "spectrogram-frequency-limits": true,
    "spectrogram-frequency-scale": true,
    "spectrogram-power-limits": true,
    "inspector-ui": true,
    "multi-page-element": true,
    "graph-output-zone": true,
    "output-loading-flow": true,
    "dialog-system": false,
    "file-browser-dialog": false,
    "session-import-export-ui": false,
    "object-export-dialog": false,
    "reference-scenarios": true,
    // The legacy four-card specs remain loadable but must not run against the
    // single-graph-per-Display workflow.
    "legacy-fixed-workspace": false,
    "signal-analyser-displays": true,
  },
};
