"use strict";
const fs=require("fs"),path=require("path");const ROOT=path.join(__dirname,"artifacts","HND-0375"),TARGET="https://engee.com/prod/user/demo54365638-bogoslm/genie/signal_analyser/";
const r={handoff_id:"HND-0375",phase:"popup-followup",checks:[],network_failures:[],screenshots:[],started_at:new Date().toISOString()};const add=(name,pass,actual,expected)=>r.checks.push({name,pass:!!pass,actual,expected});
(async()=>{const ts=await(await fetch("http://127.0.0.1:9222/json/list")).json(),t=ts.find(x=>x.type==="page"&&x.url===TARGET);if(!t)throw Error("production target absent");const ws=new WebSocket(t.webSocketDebuggerUrl);await new Promise((ok,bad)=>{ws.onopen=ok;ws.onerror=bad});let n=0;const q=new Map;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=q.get(m.id);if(p){q.delete(m.id);m.error?p.bad(Error(m.error.message)):p.ok(m.result||{})}}else if(m.method==="Network.responseReceived"&&m.params.response.status>=400)r.network_failures.push({url:m.params.response.url,status:m.params.response.status,type:m.params.type})};const call=(method,params={})=>new Promise((ok,bad)=>{const id=++n;q.set(id,{ok,bad});ws.send(JSON.stringify({id,method,params}))});const ev=async s=>(await call("Runtime.evaluate",{expression:s,returnByValue:true,awaitPromise:true})).result.value;const click=async id=>{const b=await ev(`(()=>{const e=document.querySelector('[data-testid="${id}"]');if(!e)return null;const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);if(!b)throw Error("missing "+id);await call("Input.dispatchMouseEvent",{type:"mousePressed",x:b.x,y:b.y,button:"left",clickCount:1});await call("Input.dispatchMouseEvent",{type:"mouseReleased",x:b.x,y:b.y,button:"left",clickCount:1})};const esc=async()=>{await call("Input.dispatchKeyEvent",{type:"keyDown",key:"Escape",code:"Escape"});await call("Input.dispatchKeyEvent",{type:"keyUp",key:"Escape",code:"Escape"})};const shot=async name=>{const x=await call("Page.captureScreenshot",{format:"png"});const f=path.join(ROOT,name);fs.writeFileSync(f,Buffer.from(x.data,"base64"));r.screenshots.push(f)};
await call("Page.enable");await call("Network.enable");await call("Page.bringToFront");
await click("signal-columns-menu-trigger");const menu=await ev(`(()=>{const e=document.querySelector('[data-testid="signal-columns-menu"]'),x=document.querySelector('[data-testid="signal-column-toggle-color"]');return{open:!!e&&!e.hidden,eyes:!!x&&!!x.querySelector('img,svg'),focus:document.activeElement&&document.activeElement.dataset.testid}})()`);add("inspector-column-menu-eye-icons",menu.open&&menu.eyes,menu,"menu opens with eye/eye-off control");await shot("production-inspector-column-menu-1440x900.png");await esc();
await click("signals-add-action");const action=await ev(`(()=>({workspace:!!document.querySelector('[data-testid="signals-add-workspace-action"]'),selection:!!document.querySelector('[data-testid="signals-add-selection-action"]')}))()`);add("signals-add-popup",action.workspace||action.selection,action,"add popup actions exist");if(action.workspace)await click("signals-add-workspace-action");const dialog=await ev(`(()=>{const e=document.querySelector('[data-testid="signals-workspace-dialog"]');return{visible:!!e&&e.getBoundingClientRect().width>0,focusInside:!!e&&e.contains(document.activeElement),active:document.activeElement&&document.activeElement.dataset.testid}})()`);add("workspace-modal-focus-owner",dialog.visible&&dialog.focusInside,dialog,"blocking dialog owns focus");await shot("production-workspace-dialog-1440x900.png");await esc();const restore=await ev(`document.activeElement&&document.activeElement.dataset.testid`);add("workspace-modal-escape-restoration",restore==="signals-add-action",restore,"Signals add focus restored");
await click("layout-trigger");await click("layout-cancel");add("layout-popover-cancel",await ev(`(()=>{const e=document.querySelector('[data-testid="layout-popover"]');return !!e.hidden||e.getBoundingClientRect().width===0})()`),null,"cancel closes popover");
r.completed_at=new Date().toISOString();r.summary={planned:r.checks.length,passed:r.checks.filter(x=>x.pass).length,failed:r.checks.filter(x=>!x.pass).length};fs.writeFileSync(path.join(ROOT,"popup-followup.json"),JSON.stringify(r,null,2));ws.close();console.log(JSON.stringify(r.summary));})().catch(e=>{r.error=String(e.stack||e);r.completed_at=new Date().toISOString();fs.writeFileSync(path.join(ROOT,"popup-followup.json"),JSON.stringify(r,null,2));console.error(r.error);process.exit(1)});
