"use strict";

const fs=require("fs"),path=require("path"),{execFileSync}=require("child_process"),{performance}=require("perf_hooks"),{chromium}=require("playwright-core");
const target="https://engee.com/prod/user/demo54365638-bogoslm/genie/signal_analyser/",expected="c049f0b8ecedc720243927dcf7cafa91e2825505",out=path.resolve(__dirname,"artifacts/HND-0610-final-binding-perf");
const R={id:"HND-0610",target,expected_revision:expected,browser_channel:"chrome",headless:false,browser_visibility:"foreground",worker_count:1,network:[],errors:[],opened_tab_count:0,closed_tab_count:0};
const now=()=>Math.round(performance.now()*10)/10,save=()=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,"report.json"),JSON.stringify(R,null,2)+"\n")};
const front=async p=>{await p.bringToFront();try{execFileSync("osascript",["-e",'tell application "Google Chrome" to activate'])}catch(_){}};
const state=p=>p.evaluate(async()=>await(await fetch("./api/state-lite",{cache:"no-store"})).json());
const normalized=s=>({active:s.active_display_id,displays:(s.displays||[]).map(x=>({id:x.id,name:x.name})),layouts:(s.layouts||[]).map(x=>({display_id:x.display_id,rows:x.layout.rows,columns:x.layout.columns,active_pane_id:x.layout.active_pane_id,panes:x.layout.panes.map(p=>({id:p.id,plot_type:p.plot_type,signal_bindings:p.signal_bindings}))}))});
const projection=(s,id)=>({display:(s.displays||[]).find(x=>x.id===id),layout:(s.layouts||[]).find(x=>x.display_id===id)?.layout,displays:(s.displays||[]).map(x=>({id:x.id,name:x.name}))});
const cx=(s,id)=>{const l=(s.layouts||[]).find(x=>x.display_id===id)?.layout;return{layout:l,pane:l&&l.panes.find(x=>x.id===l.active_pane_id)}};
const round=n=>typeof n==="number"?Math.round(n*10)/10:null;

async function probe(p,paneId,start){await p.evaluate(({paneId,start})=>{window.__hnd0610={start,events:[],longtasks:[],host:null};const mark=(n,d={})=>window.__hnd0610.events.push({name:n,at:performance.now()-start,detail:d}),inspect=()=>{const z=window.__hnd0610,s=z.seen||(z.seen={}),l=document.querySelector(`[data-testid='pane-loader-${CSS.escape(paneId)}']`),h=document.querySelector(`[data-testid='plot-host-${CSS.escape(paneId)}']`),e=document.querySelector(`[data-testid='pane-empty-${CSS.escape(paneId)}']`);if(l&&!s.l){s.l=1;mark("loader-visible")}if(h&&!s.h){s.h=1;z.host=h;mark("plot-host-created",{ready:h.dataset.plotReady})}if(h&&h.dataset.plotReady==="true"&&!s.r){s.r=1;mark("plot-ready",{sameHost:h===z.host,traces:(h.data||[]).length})}if(e&&!s.e){s.e=1;mark("empty-visible")}};new MutationObserver(inspect).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:["data-plot-ready"]});try{new PerformanceObserver(a=>a.getEntries().forEach(x=>z.longtasks.push({start:x.startTime-start,duration:x.duration}))).observe({entryTypes:["longtask"]})}catch(_){}inspect();mark("probe-installed")},{paneId,start})}

(async()=>{let b,c,p,baseline,original,tempId,paneId,signal,created=false,bound=false;try{
  fs.mkdirSync(out,{recursive:true});b=await chromium.launch({channel:"chrome",headless:false});c=b.contexts()[0]||await b.newContext();R.preexisting_page_urls=c.pages().map(x=>x.url());p=await c.newPage();R.opened_tab_count++;
  p.on("request",x=>{if(/\/api\/(?:displays|layouts|outputs\/active|settings)(?:\?|$)/.test(x.url())||x.url().includes("plotly-cartesian"))R.network.push({phase:"request",at:now(),method:x.method(),url:x.url()})});
  p.on("response",async x=>{if(!(/\/api\/(?:displays|layouts|outputs\/active|settings)(?:\?|$)/.test(x.url())||x.url().includes("plotly-cartesian")))return;const q={phase:"response",at:now(),method:x.request().method(),status:x.status(),url:x.url()};try{const z=await x.body();q.bytes=z.length;if(x.url().includes("/outputs/active")){const j=JSON.parse(z);q.output={isready:j.isready,success:j.success,state_revision:j.state_revision,calculation_revision:j.calculation_revision}}}catch(e){}R.network.push(q);save()});
  p.on("pageerror",e=>R.errors.push("pageerror: "+e));p.on("console",m=>{if(m.type()==="error"&&!/favicon/.test(m.text()))R.errors.push("console: "+m.text())});
  await p.setViewportSize({width:1440,height:900});await front(p);const navStart=now(),root=await p.goto(target,{waitUntil:"domcontentloaded",timeout:120000});await p.getByTestId("app-shell").waitFor({state:"visible",timeout:180000});
  const gate=await p.evaluate(async()=>{const x=await fetch("./api/status",{cache:"no-store"});return{status:x.status,body:await x.json()}});if(!root||root.status()!==200||gate.status!==200||!gate.body.ready||gate.body.runtime_revision!==expected)throw Error("revision gate "+JSON.stringify({root:root&&root.status(),gate}));R.revision_gate=gate;
  baseline=await state(p);original=baseline.active_display_id;R.external_baseline={normalized:normalized(baseline),projection:projection(baseline,original)};
  const beforeIds=baseline.displays.map(x=>x.id),createWait=p.waitForResponse(x=>/\/api\/displays(?:\?|$)/.test(x.url())&&x.request().method()==="POST",{timeout:60000});await p.getByTestId("add-display").click();if((await createWait).status()!==200)throw Error("create failed");
  const createdState=await state(p),newIds=createdState.displays.map(x=>x.id).filter(id=>!beforeIds.includes(id));if(newIds.length!==1)throw Error("unsafe identity "+JSON.stringify(newIds));tempId=newIds[0];created=true;const t=cx(createdState,tempId);if(createdState.active_display_id!==tempId||t.layout.rows!==1||t.layout.columns!==1||t.layout.panes.length!==1||t.pane.signal_bindings.length)throw Error("temp not empty 1x1");paneId=t.pane.id;signal=createdState.signals.find(x=>x.name==="Гармонический сигнал")?.name;if(!signal)throw Error("signal missing");R.temporary={display_id:tempId,pane_id:paneId,signal};
  await p.getByTestId("inspector-tab-signals").click();
  // Let only normal bootstrap/idle work settle; no artificial wait.
  await p.evaluate(()=>new Promise(ok=>requestAnimationFrame(()=>requestAnimationFrame(ok))));
  const clickAt=now(),preloadEntries=await p.evaluate(()=>performance.getEntriesByType("resource").filter(x=>x.name.includes("plotly-cartesian")).map(x=>({name:x.name,startTime:x.startTime,responseEnd:x.responseEnd,duration:x.duration,transferSize:x.transferSize,decodedBodySize:x.decodedBodySize}))),preBindNetwork=R.network.slice();
  const empty=await p.evaluate(id=>({emptyCopy:document.querySelector(`[data-testid='pane-empty-${CSS.escape(id)}']`)?.textContent.trim(),hosts:document.querySelectorAll(`[data-testid='plot-host-${CSS.escape(id)}'],[data-pane-host]`).length,hiddenPlots:document.querySelectorAll(".js-plotly-plot").length,windowPlotly:!!window.Plotly}),paneId);
  const tempOutputsBefore=preBindNetwork.filter(x=>x.url.includes("/outputs/active")&&x.url.includes(`display_id=${tempId}`));
  R.pre_bind={nav_to_click_ms:round(clickAt-navStart),empty,plotly_resources:preloadEntries,plotly_preload_completed_before_click:preloadEntries.some(x=>x.responseEnd>0),temp_output_requests:tempOutputsBefore};
  const browserStart=await p.evaluate(()=>performance.now());await probe(p,paneId,browserStart);const n=R.network.length,cb=p.locator(`input[data-visible-signal='${signal.replace(/'/g,"\\'")}']`),layoutWait=p.waitForResponse(x=>/\/api\/layouts(?:\?|$)/.test(x.url())&&x.request().method()==="POST",{timeout:60000});await cb.check();bound=true;const clicked=now(),layoutRes=await layoutWait,layoutAt=now();await p.waitForFunction(id=>{const h=document.querySelector(`[data-testid='plot-host-${CSS.escape(id)}']`);return h&&h.dataset.plotReady==="true"},paneId,{timeout:180000});const terminal=now();await p.evaluate(()=>new Promise(ok=>requestAnimationFrame(()=>requestAnimationFrame(ok))));const dom=await p.evaluate(()=>window.__hnd0610),net=R.network.slice(n).map(x=>({...x,since:round(x.at-clickAt)})),outs=net.filter(x=>x.url.includes("/outputs/active")),reqs=outs.filter(x=>x.phase==="request"),resps=outs.filter(x=>x.phase==="response"),pending=resps.find(x=>x.output&&!x.output.isready),ready=resps.find(x=>x.output&&x.output.isready&&x.output.success),gaps=[];for(let i=0;i<reqs.length-1;i++){const r=resps.find(x=>x.at>=reqs[i].at&&x.at<=reqs[i+1].at);if(r&&r.output&&!r.output.isready)gaps.push(round(reqs[i+1].at-r.at))}const pr=dom.events.find(x=>x.name==="plot-ready"),scriptEntries=await p.evaluate(()=>performance.getEntriesByType("resource").filter(x=>x.name.includes("plotly-cartesian")).map(x=>({name:x.name,startTime:x.startTime,responseEnd:x.responseEnd,duration:x.duration,transferSize:x.transferSize,decodedBodySize:x.decodedBodySize})));
  R.first_bind={click_action_ms:round(clicked-clickAt),layouts_status:layoutRes.status(),layouts_response_ms:round(layoutAt-clickAt),first_pending_ms:pending&&pending.since,ready_ms:ready&&ready.since,ready_to_plot_ms:ready&&pr?round(pr.at-ready.since):null,plot_ready_ms:pr&&round(pr.at),terminal_ms:round(terminal-clickAt),adaptive_waits_ms:gaps,output_request_count:reqs.length,output_responses:resps.map(x=>({isready:x.output?.isready,bytes:x.bytes,since:x.since})),settings_get_count:net.filter(x=>x.method==="GET"&&/\/api\/settings(?:\?|$)/.test(x.url)).length,target_only_no_fanout:outs.every(x=>x.url.includes(`display_id=${tempId}`)&&x.url.includes(`pane_id=${paneId}`)),dom_events:dom.events.map(x=>({...x,at:round(x.at)})),longtasks:dom.longtasks,plotly_resources_after:scriptEntries,network:net};
  await p.screenshot({path:path.join(out,"first-bind-ready.png"),animations:"disabled"});R.screenshot="first-bind-ready.png";
}catch(e){R.errors.push(String(e&&e.stack||e))}finally{
  if(p&&!p.isClosed()&&created&&tempId){try{await front(p);const s=await state(p);if(s.displays.some(x=>x.id===tempId)){if(s.active_display_id!==tempId)await p.getByTestId(`display-tab-${tempId}`).click();if(bound&&paneId&&signal){await p.getByTestId("inspector-tab-signals").click();const cb=p.locator(`input[data-visible-signal='${signal.replace(/'/g,"\\'")}']`);if(await cb.count()&&await cb.isChecked()){const w=p.waitForResponse(x=>/\/api\/layouts(?:\?|$)/.test(x.url())&&x.request().method()==="POST",{timeout:60000});await cb.uncheck();await w;bound=false}}const w=p.waitForResponse(x=>/\/api\/displays(?:\?|$)/.test(x.url())&&x.request().method()==="POST",{timeout:60000});await p.getByTestId(`display-close-${tempId}`).click();if((await w).status()!==200)throw Error("close failed");await p.waitForFunction(id=>!document.querySelector(`[data-testid='display-tab-${CSS.escape(id)}']`),tempId,{timeout:60000})}const f=await state(p);R.final={normalized:normalized(f),projection:projection(f,original)};R.restoration={temporary_removed:!f.displays.some(x=>x.id===tempId),original_active:f.active_display_id===original,external_projection_byte_for_byte:JSON.stringify(R.final.projection)===JSON.stringify(R.external_baseline.projection),normalized_byte_for_byte:JSON.stringify(R.final.normalized)===JSON.stringify(R.external_baseline.normalized)}}catch(e){R.errors.push("restoration: "+String(e&&e.stack||e))}}
  if(p&&!p.isClosed()){try{await p.close();R.closed_tab_count++}catch(e){R.errors.push("cleanup: "+e)}}R.tab_cleanup_status=R.opened_tab_count===R.closed_tab_count?"passed":"failed";save();if(b)await b.close();console.log(JSON.stringify({pre_bind:R.pre_bind,first_bind:R.first_bind,restoration:R.restoration,errors:R.errors,cleanup:R.tab_cleanup_status},null,2));if(R.errors.length||!R.restoration?.external_projection_byte_for_byte||R.tab_cleanup_status!=="passed")process.exitCode=1}})();
