"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "artifacts", "HND-0375");
const TARGET = "https://engee.com/prod/user/demo54365638-bogoslm/genie/signal_analyser/";
const SHA = "545bef2d6f5fbf76f32f6afb4bfe88f6a962e48c";
const VIEWS = [[1024,768],[1280,720],[1440,900]];
const report={handoff_id:"HND-0375",mode:"new_functionality_regression",target:TARGET,expected_revision:SHA,browser_channel:"chrome",headless:false,browser_visibility:"foreground",worker_count:1,started_at:new Date().toISOString(),checks:[],pageerrors:[],console_errors:[],screenshots:[]};
function check(name,pass,actual,expected){report.checks.push({name,pass:!!pass,actual,expected});}
async function main(){
  fs.mkdirSync(ROOT,{recursive:true});
  const targets=await (await fetch("http://127.0.0.1:9222/json/list")).json();
  const target=targets.find(t=>t.type==="page"&&t.url===TARGET); if(!target)throw Error("Exact production target is absent from visible Chrome");
  const ws=new WebSocket(target.webSocketDebuggerUrl); await new Promise((ok,bad)=>{ws.onopen=ok;ws.onerror=bad;});
  let id=0; const pending=new Map();
  ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const {ok,bad}=pending.get(m.id);pending.delete(m.id);m.error?bad(Error(m.error.message)):ok(m.result||{});}else if(m.method==="Runtime.exceptionThrown")report.pageerrors.push(m.params.exceptionDetails.text||"Runtime exception");else if(m.method==="Log.entryAdded"&&m.params.entry.level==="error")report.console_errors.push(m.params.entry.text);};
  const call=(method,params={})=>new Promise((ok,bad)=>{const n=++id;pending.set(n,{ok,bad});ws.send(JSON.stringify({id:n,method,params}));});
  const evalx=async expression=>{const r=await call("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result.value;};
  const click=async testid=>{const r=await evalx(`(()=>{const e=document.querySelector('[data-testid="${testid}"]');if(!e)return null;const r=e.getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2,w:r.width,h:r.height}})()`);if(!r)throw Error(`missing ${testid}`);await call("Input.dispatchMouseEvent",{type:"mousePressed",x:r.x,y:r.y,button:"left",clickCount:1});await call("Input.dispatchMouseEvent",{type:"mouseReleased",x:r.x,y:r.y,button:"left",clickCount:1});return r;};
  const key=async k=>{await call("Input.dispatchKeyEvent",{type:"keyDown",key:k,code:k==="Escape"?"Escape":k});await call("Input.dispatchKeyEvent",{type:"keyUp",key:k,code:k==="Escape"?"Escape":k});};
  const shot=async name=>{const d=await call("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});const f=path.join(ROOT,name);fs.writeFileSync(f,Buffer.from(d.data,"base64"));report.screenshots.push(f);};
  await call("Page.enable");await call("Runtime.enable");await call("Log.enable");await call("Page.bringToFront");
  await call("Page.reload",{ignoreCache:true});
  await evalx(`new Promise((resolve,reject)=>{const end=Date.now()+30000;(function f(){const h=document.querySelector('[data-testid="active-plot-host"]');if(h&&h.dataset.plotReady==='true'&&h._fullLayout&&h._fullData)return resolve(true);Date.now()>end?reject(new Error('ready timeout')):requestAnimationFrame(f)})()})`);
  const status=await evalx(`fetch('./api/status',{headers:{Accept:'application/json'},cache:'no-store'}).then(async r=>({url:r.url,status:r.status,body:await r.json()}))`);report.status=status;check("availability-exact-revision",status.status===200&&status.body.ready===true&&status.body.ok===true&&status.body.runtime_revision===SHA,status,"ready/ok and exact SHA");
  const live=await evalx(`(()=>{const h=document.querySelector('[data-testid="active-plot-host"]');return {fullLayout:!!h._fullLayout,fullData:!!h._fullData,staticPlot:h._context.staticPlot,fixedrange:!!h._fullLayout.xaxis.fixedrange,svg:!!h.querySelector('svg.main-svg'),modebar:!!h.querySelector('.modebar,.modebar-container')};})()`);check("live-local-plotly",live.fullLayout&&live.fullData&&live.staticPlot===false&&live.fixedrange===false&&live.svg&&!live.modebar,live,"interactive Plotly");
  for(const [w,h] of VIEWS){await call("Emulation.setDeviceMetricsOverride",{width:w,height:h,deviceScaleFactor:1,mobile:false});await call("Page.bringToFront");const zones=await evalx(`(()=>['app-shell','display-workspace','display-canvas','display-settings','bottom-panel-signals'].map(id=>{const e=document.querySelector('[data-testid="'+id+'"]'),r=e&&e.getBoundingClientRect();return {id,box:r&&[r.x,r.y,r.width,r.height]}}))()`);check(`five-zones-${w}x${h}`,zones.every(z=>z.box&&z.box[2]>0&&z.box[3]>0),zones,"five nonzero zones");const labels=await evalx(`(()=>['Настройки отображения','Отображение','Время','Измерения','Тип графика','Сигналы'].every(x=>document.body.innerText.includes(x)))()`);check(`russian-labels-${w}x${h}`,labels,labels,"Russian settings labels");await shot(`production-default-${w}x${h}.png`);}
  await call("Emulation.setDeviceMetricsOverride",{width:1440,height:900,deviceScaleFactor:1,mobile:false});
  const p=await evalx(`(()=>{const e=document.querySelector('[data-testid="active-plot-host"]'),r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,ranges:[e._fullLayout.xaxis.range,e._fullLayout.yaxis.range]}})()`);
  const getRanges=()=>evalx(`(()=>{const e=document.querySelector('[data-testid="active-plot-host"]');return[e._fullLayout.xaxis.range,e._fullLayout.yaxis.range]})()`);
  await call("Input.dispatchMouseEvent",{type:"mousePressed",x:p.x+p.w*.25,y:p.y+p.h*.3,button:"left",clickCount:1});await call("Input.dispatchMouseEvent",{type:"mouseMoved",x:p.x+p.w*.75,y:p.y+p.h*.7,button:"left"});await call("Input.dispatchMouseEvent",{type:"mouseReleased",x:p.x+p.w*.75,y:p.y+p.h*.7,button:"left",clickCount:1});const zoom=await getRanges();check("plotly-LMB-zoom",JSON.stringify(zoom)!==JSON.stringify(p.ranges),{initial:p.ranges,zoom},"range changes");
  await call("Input.dispatchMouseEvent",{type:"mousePressed",x:p.x+p.w*.5,y:p.y+p.h*.5,button:"left",clickCount:2});await call("Input.dispatchMouseEvent",{type:"mouseReleased",x:p.x+p.w*.5,y:p.y+p.h*.5,button:"left",clickCount:2});const reset=await getRanges();check("plotly-double-click-autoscale",JSON.stringify(reset)===JSON.stringify(p.ranges),{initial:p.ranges,reset},"range reset");
  await call("Input.dispatchKeyEvent",{type:"keyDown",key:"Shift",code:"ShiftLeft",windowsVirtualKeyCode:16});await call("Input.dispatchMouseEvent",{type:"mousePressed",x:p.x+p.w*.45,y:p.y+p.h*.45,button:"left",clickCount:1});await call("Input.dispatchMouseEvent",{type:"mouseMoved",x:p.x+p.w*.6,y:p.y+p.h*.55,button:"left",modifiers:8});await call("Input.dispatchMouseEvent",{type:"mouseReleased",x:p.x+p.w*.6,y:p.y+p.h*.55,button:"left",clickCount:1,modifiers:8});await call("Input.dispatchKeyEvent",{type:"keyUp",key:"Shift",code:"ShiftLeft",windowsVirtualKeyCode:16});const pan=await getRanges();check("plotly-Shift-LMB-pan",JSON.stringify(pan)!==JSON.stringify(reset),{reset,pan},"range translates");await shot("production-plotly-gestures-1440x900.png");
  const before=await evalx(`(()=>{const r=document.querySelector('[data-testid="active-plot-host"]').getBoundingClientRect();return[r.x,r.y,r.width,r.height]})()`);await click("display-overflow-trigger");check("pane-menu",await evalx(`!!document.querySelector('[data-testid="display-overflow-menu"]:not([hidden])')`),null,"visible");await click("graph-help-action");const help=await evalx(`(()=>{const e=[...document.querySelectorAll('*')].find(e=>e.textContent==='Перетаскивать график: Shift + ЛКМ');const r=e&&e.getBoundingClientRect(),hit=r&&document.elementFromPoint(r.x+4,r.y+4);return{visible:!!r&&r.width>0,hit:!!hit&&e.parentElement.contains(hit),focus:document.activeElement&&document.activeElement.getAttribute('data-testid'),plot:(()=>{const q=document.querySelector('[data-testid="active-plot-host"]').getBoundingClientRect();return[q.x,q.y,q.width,q.height]})()}})()`);check("graph-help-hit-focus-no-shift",help.visible&&help.hit&&JSON.stringify(before)===JSON.stringify(help.plot),help,"top hit and unchanged plot");await shot("production-graph-help-1440x900.png");await key("Escape");await key("Escape");
  await click("layout-trigger");const lay=await evalx(`(()=>{const e=document.querySelector('[data-testid="layout-popover"]'),r=e.getBoundingClientRect();return{visible:!!r&&r.width>0,hit:!!document.elementFromPoint(r.x+4,r.y+4).closest('[data-testid="layout-popover"]')}})()`);await call("Input.dispatchMouseEvent",{type:"mousePressed",x:2,y:100,button:"left",clickCount:1});await call("Input.dispatchMouseEvent",{type:"mouseReleased",x:2,y:100,button:"left",clickCount:1});const closed=await evalx(`(()=>{const e=document.querySelector('[data-testid="layout-popover"]');return!!e.hidden||e.getBoundingClientRect().width===0})()`);check("layout-popover-hit-outside-dismiss",lay.visible&&lay.hit&&closed,{lay,closed},"hit owner then outside dismissal");
  check("zero-js-errors",!report.pageerrors.length&&!report.console_errors.length,{pageerrors:report.pageerrors,console:report.console_errors},"no JS errors");
  report.completed_at=new Date().toISOString();report.summary={planned:report.checks.length,passed:report.checks.filter(c=>c.pass).length,failed:report.checks.filter(c=>!c.pass).length};report.summary.success_rate=report.summary.passed/report.summary.planned*100;fs.writeFileSync(path.join(ROOT,"evidence-cdp.json"),JSON.stringify(report,null,2));ws.close();console.log(JSON.stringify(report.summary));
}
main().catch(e=>{report.error=String(e.stack||e);report.completed_at=new Date().toISOString();fs.writeFileSync(path.join(ROOT,"evidence-cdp.json"),JSON.stringify(report,null,2));console.error(report.error);process.exit(1);});
