"use strict";
// TASK-0088: production-only, visible-Chrome regression evidence.  This file
// owns neither product source nor pre-existing browser pages.
const fs = require("fs"), path = require("path"), assert = require("assert");
const { execFileSync } = require("child_process");
const { chromium } = require("playwright-core");

const TARGET = "https://engee.com/prod/user/demo54365638-bogoslm/genie/signal_analyser/";
const REVISION = "568a29f48edbfb2bb5f8ad3eaeea089c34a910ea";
const PROTOTYPE = `file://${path.resolve("architecture/design/TASK-0080-explicit-apply-flow/prototype/index.html")}`;
const OUT = path.resolve("test/playwright/artifacts/TASK-0088");
fs.mkdirSync(OUT, { recursive: true });

const report = { id:"HND-TASK-0088-E2E-REPORT", type:"report", from:"E2E", to:"Orchestrator",
  title:"TASK-0088 foreground production regression", e2e_mode:"new_functionality_regression",
  target:TARGET, expected_revision:REVISION, design_ref:"architecture/design/TASK-0080-explicit-apply-flow/DESIGN.md", design_version:5,
  prototype_entry:PROTOTYPE, applied_skills:["e2e/e2e-workflow","e2e/visual-analysis"], browser_channel:"chrome", headless:false,
  browser_visibility:"foreground", worker_count:1, started_at:new Date().toISOString(), checks:[], screenshots:[], network:[], console_errors:[], page_errors:[],
  opened_tab_count:0, closed_tab_count:0, tab_cleanup_status:"pending", remaining_mutations:[] };
const check=(name, pass, detail={})=>report.checks.push({name,status:pass?"passed":"failed",detail});
const visible = n => n && (()=>{const s=getComputedStyle(n),b=n.getBoundingClientRect();return !n.hidden&&s.display!=="none"&&s.visibility!=="hidden"&&b.width>0&&b.height>0;})();
async function front(page){ await page.bringToFront(); try { execFileSync("osascript",["-e",'tell application "Google Chrome" to activate']); report.chrome_activation="ok"; } catch(e) { report.chrome_activation_error=String(e); } }
async function shot(page,file,state){ await front(page); const full=path.join(OUT,file); await page.screenshot({path:full,fullPage:false}); report.screenshots.push({file,target:page.url(),viewport:page.viewportSize(),state,timestamp:new Date().toISOString()}); }
function observe(page){ page.on("console",m=>{if(m.type()==="error")report.console_errors.push({text:m.text(),url:m.location().url,line:m.location().lineNumber});}); page.on("pageerror",e=>report.page_errors.push(String(e))); page.on("response",r=>{const main=r.request().isNavigationRequest()&&r.frame()===page.mainFrame(); if(main||r.status()>=400||/\/api\/(state-lite|settings|settings\/apply|layouts)/.test(r.url())) report.network.push({status:r.status(),method:r.request().method(),url:r.url(),main_document:main});}); }
async function state(page){ return page.evaluate(async()=>{const r=await fetch("./api/state-lite",{headers:{Accept:"application/json","Cache-Control":"no-cache"},cache:"no-store"});const text=await r.text();let body;try{body=JSON.parse(text)}catch(_){body={raw:text.slice(0,1000)}}return {status:r.status,body};}); }
function activeLayout(s){const b=s.body||s; const d=(b.displays||[]).find(x=>x.id===b.active_display_id);const e=(b.layouts||[]).find(x=>x.display_id===(d&&d.id));return {display:d,entry:e,layout:e&&e.layout};}
async function waitReady(page, expected){ await page.waitForFunction(exp=>{const panes=[...document.querySelectorAll("[data-testid^='plot-pane-'], .plot-pane")].filter(p=>{const s=getComputedStyle(p),b=p.getBoundingClientRect();return !p.hidden&&s.display!=="none"&&s.visibility!=="hidden"&&b.width>0&&b.height>0;}); if(!panes.length)return false; return panes.every(p=>{const host=p.querySelector("[data-testid='active-plot-host'],[data-plot-ready],.js-plotly-plot"); return host && (host.dataset.plotReady==="true" || host.classList.contains("js-plotly-plot"));}) && (!exp || panes.length===exp);}, expected, {timeout:60000}).catch(e=>{throw new Error("Plotly ready panes: "+e.message);}); }
async function setLayout(page,rows,columns){ await front(page); const popover=page.getByTestId("layout-popover"); if(!await popover.isVisible()) await page.getByTestId("layout-trigger").click(); await popover.waitFor({state:"visible",timeout:15000}); const choose=async(axis,n)=>{const b=page.locator(`button[data-layout-${axis}="${n}"]`);await b.waitFor({state:"visible",timeout:15000});if(await b.getAttribute("aria-pressed")!=="true")await b.click();}; await choose("rows",rows); await choose("columns",columns); const response=page.waitForResponse(r=>/\/api\/layouts$/.test(new URL(r.url()).pathname)&&r.request().method()==="POST",{timeout:30000}); await page.getByTestId("layout-apply").click(); const r=await response; check(`layout ${rows}x${columns} API response`,r.ok(),{status:r.status(),url:r.url()}); await popover.waitFor({state:"hidden",timeout:15000}); }
async function selectPlot(page,type){const select=page.getByTestId("settings-field-display.plot_type").locator("select");await select.waitFor({state:"visible",timeout:20000});const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith("/api/layouts")&&r.request().method()==="POST",{timeout:30000});await select.selectOption(type);const r=await response; if(!r.ok())throw Error(`plot type POST ${r.status()}`);await page.waitForFunction(t=>{const n=document.querySelector("[data-testid='settings-field-display.plot_type'] select");return n&&n.value===t;},type,{timeout:15000});}
async function prototypeLayout(page){
  for(const vp of [{width:1024,height:768},{width:1280,height:720},{width:1440,height:900}]) { await page.setViewportSize(vp); await front(page); const trigger=page.locator("[data-design-id='layout-trigger'],[data-testid='layout-trigger']").first(); await trigger.click(); const dialog=page.locator("[data-design-id='layout-popover'],[data-testid='layout-popover']").first(); await dialog.waitFor({state:"visible"}); const x=await dialog.evaluate(n=>{const b=n.getBoundingClientRect(),s=getComputedStyle(n);return {w:b.width,x:b.x,y:b.y,position:s.position,radius:s.borderRadius,inViewport:b.x>=0&&b.y>=0&&b.right<=innerWidth&&b.bottom<=innerHeight};}); check(`prototype v5 dialog geometry ${vp.width}x${vp.height}`,Math.abs(x.w-372)<=2&&x.inViewport,{...x}); await shot(page,`prototype-layout-open-${vp.width}x${vp.height}.png`,`prototype open ${vp.width}x${vp.height}`); await page.keyboard.press("Escape"); await dialog.waitFor({state:"hidden"}); check(`prototype Escape restores layout trigger ${vp.width}x${vp.height}`,await trigger.evaluate(n=>document.activeElement===n),{}); }
}
async function dialogLifecycle(page){
  const trigger=page.getByTestId("layout-trigger"), dialog=page.getByTestId("layout-popover"); const original=(await state(page)).body;
  for(const how of ["repeat","cancel","escape","outside"]) { await front(page); await trigger.click(); await dialog.waitFor({state:"visible"}); const d=await dialog.evaluate(n=>{const b=n.getBoundingClientRect(),s=getComputedStyle(n);return {w:b.width,x:b.x,y:b.y,position:s.position,radius:s.borderRadius,clamp:b.x>=0&&b.y>=0&&b.right<=innerWidth&&b.bottom<=innerHeight};}); if(how==="repeat"){await trigger.click(); await dialog.waitFor({state:"hidden"});} else if(how==="cancel"){await page.getByTestId("layout-cancel").click(); await dialog.waitFor({state:"hidden"});} else if(how==="escape"){await page.keyboard.press("Escape"); await dialog.waitFor({state:"hidden"});} else {await page.mouse.click(4,4);await dialog.waitFor({state:"hidden"});} const now=(await state(page)).body; check(`layout dialog ${how}: close, focus restore, no draft leak`,Math.abs(d.w-372)<=2&&d.clamp&&await trigger.evaluate(n=>document.activeElement===n)&&JSON.stringify(now.layouts)===JSON.stringify(original.layouts),{geometry:d,focus:await trigger.evaluate(n=>document.activeElement===n)}); }
  await front(page); await trigger.click(); await dialog.waitFor({state:"visible"}); await shot(page,"production-layout-dialog.png","layout dialog open");
}
async function addDisplay(page){ const before=(await state(page)).body.displays.length; const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith("/api/layouts")&&r.request().method()==="POST",{timeout:30000}).catch(()=>null); await page.getByTestId("add-display").click(); await page.waitForFunction(n=>document.querySelectorAll("[data-testid^='display-tab-'],.display-tab-shell").length>=n,before+1,{timeout:15000}); await response; return (await state(page)).body; }
async function clickDisplay(page,id){const loc=page.locator(`.display-tab-shell[data-screen-id=${JSON.stringify(String(id))}] [role=tab], [data-testid='display-tab-${id}']`).first();await loc.click();await page.waitForFunction(expected=>{const n=document.querySelector(`.display-tab-shell[data-screen-id="${expected}"]`);return n&&n.classList.contains("is-selected");},String(id),{timeout:15000});}
async function closeDisplay(page,id){const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith("/api/displays")&&r.request().method()==="POST",{timeout:30000});await page.getByTestId(`display-close-${id}`).click();const r=await response;if(!r.ok())throw Error(`close ${id}: ${r.status()}`);await page.waitForFunction(expected=>!document.querySelector(`[data-testid="display-tab-${expected}"]`),String(id),{timeout:15000});}
async function restoreBaseline(page){
  let current=(await state(page)).body;
  for(const display of current.displays.filter(d=>d.id!=="display-1")) await closeDisplay(page,display.id);
  current=(await state(page)).body;
  if(current.active_display_id!=="display-1")await clickDisplay(page,"display-1");
  const layout=activeLayout(await state(page)).layout;
  if(layout.rows!==1||layout.columns!==1)await setLayout(page,1,1);
}
async function main(){let browser,context,prototype,prod;const tracked=new Set();let initial;
 try { browser=await chromium.launch({channel:"chrome",headless:false}); context=browser.contexts()[0]||await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1}); report.preexisting_pages=context.pages().map(p=>p.url()); report.preexisting_page_count=report.preexisting_pages.length;
   prototype=await context.newPage();tracked.add(prototype);report.opened_tab_count++;observe(prototype);await prototype.setViewportSize({width:1440,height:900});await front(prototype);await prototype.goto(PROTOTYPE,{waitUntil:"load",timeout:30000});await prototypeLayout(prototype);
   prod=await context.newPage();tracked.add(prod);report.opened_tab_count++;observe(prod);await prod.setViewportSize({width:1440,height:900});await front(prod);const mainResponse=await prod.goto(TARGET,{waitUntil:"domcontentloaded",timeout:60000});report.main_document={status:mainResponse&&mainResponse.status(),url:prod.url(),timestamp:new Date().toISOString()};await prod.getByTestId("app-shell").waitFor({state:"visible",timeout:60000}); const status=await prod.evaluate(async()=>{const r=await fetch("./api/status",{cache:"no-store"});const text=await r.text();let b;try{b=JSON.parse(text)}catch(_){b={raw:text.slice(0,1000)}}return {status:r.status,body:b};});report.runtime_status=status;const revisionOk=status.status===200&&status.body.runtime_revision===REVISION;check("availability and exact runtime revision",revisionOk,{main_document:report.main_document,status});if(!revisionOk)throw Error("BLOCKER: target unavailable or exact runtime revision missing");
   const appError=await prod.getByTestId("app-error").isVisible().catch(()=>false);const technical=appError||/техническ|maintenance/i.test(await prod.locator("body").innerText());if(technical){await shot(prod,"production-maintenance.png","availability failure");throw Error("BLOCKER: technical/maintenance screen");}
   await prod.locator("[data-settings-group-toggle]").first().waitFor({state:"visible",timeout:60000}); await restoreBaseline(prod); initial=(await state(prod)).body;report.initial_state={active_display_id:initial.active_display_id,displays:initial.displays,layouts:initial.layouts};await shot(prod,"production-ready-1440x900.png","ready initial"); await dialogLifecycle(prod); await prod.getByTestId("layout-cancel").click();
   const originalActive=activeLayout({body:initial}); const afterAdd=await addDisplay(prod); const second=afterAdd.displays.find(d=>d.id!==originalActive.display.id); check("second Display created",!!second,{displays:afterAdd.displays}); await setLayout(prod,1,2);await waitReady(prod,2);const secondLayout=activeLayout(await state(prod)); await shot(prod,"production-display2-1x2-ready.png","second display 1x2 ready"); await clickDisplay(prod,originalActive.display.id);await setLayout(prod,1,3);await waitReady(prod,3);const firstLayout=activeLayout(await state(prod)); await clickDisplay(prod,second.id);const restoredSecond=activeLayout(await state(prod));check("Display layout isolation and restoration",firstLayout.layout.rows===1&&firstLayout.layout.columns===3&&secondLayout.layout.rows===1&&secondLayout.layout.columns===2&&restoredSecond.layout.rows===1&&restoredSecond.layout.columns===2,{first:firstLayout.layout,second:secondLayout.layout,restored:restoredSecond.layout});
   await front(prod);await clickDisplay(prod,second.id); const multi=activeLayout(await state(prod)); const paneIds=multi.layout.panes.map(p=>p.id);await waitReady(prod,paneIds.length);const ready=await prod.evaluate(()=>[...document.querySelectorAll("[data-testid^='plot-pane-'],.plot-pane")].map(p=>({id:p.dataset.paneId||p.dataset.testid,plotly:!!p.querySelector(".js-plotly-plot"),ready:p.querySelector("[data-plot-ready]")?.dataset.plotReady,empty:!!p.querySelector(".plot-empty"),loader:!!p.querySelector(".plot-initial-loading")})));check("every visible multi-pane reaches ready Plotly",ready.length===paneIds.length&&ready.every(x=>x.plotly||x.ready==="true")&&ready.every(x=>!x.empty&&!x.loader),{paneIds,ready});await shot(prod,"production-multipane-ready.png","all panes ready");
   const membershipBefore=activeLayout(await state(prod)); const signalToggle=prod.locator("[data-visible-signal='Гармонический сигнал']");const membershipOff=prod.waitForResponse(r=>new URL(r.url()).pathname.endsWith("/api/layouts")&&r.request().method()==="POST",{timeout:30000});await signalToggle.uncheck();await membershipOff;const membershipChanged=activeLayout(await state(prod));const changedPane=membershipChanged.layout.panes.find(p=>p.id===membershipChanged.layout.active_pane_id);const membershipLocal=!changedPane.signal_bindings.length&&membershipChanged.layout.panes.filter(p=>p.id!==changedPane.id).every(p=>JSON.stringify(p.signal_bindings)===JSON.stringify(membershipBefore.layout.panes.find(q=>q.id===p.id).signal_bindings));const membershipOther=JSON.stringify((await state(prod)).body.layouts.find(x=>x.display_id===originalActive.display.id))===JSON.stringify(firstLayout.entry);check("pane signal membership change is local to its pane and Display",membershipLocal&&membershipOther,{before:membershipBefore.layout,after:membershipChanged.layout});const membershipOn=prod.waitForResponse(r=>new URL(r.url()).pathname.endsWith("/api/layouts")&&r.request().method()==="POST",{timeout:30000});await signalToggle.check();await membershipOn;await waitReady(prod,paneIds.length);
   const otherBefore=JSON.stringify((await state(prod)).body.layouts.find(x=>x.display_id===originalActive.display.id)); const selectedBefore=activeLayout(await state(prod)); await prod.locator("[data-testid^='plot-pane-'],.plot-pane").nth(0).click(); const beforeType=activeLayout(await state(prod)); const alternative=beforeType.layout.panes.find(p=>p.id===beforeType.layout.active_pane_id).plot_type==="spectrum"?"time":"spectrum";await selectPlot(prod,alternative);const afterType=activeLayout(await state(prod));const siblingsUnchanged=afterType.layout.panes.filter(p=>p.id!==afterType.layout.active_pane_id).every(p=>{const old=beforeType.layout.panes.find(q=>q.id===p.id);return old&&old.plot_type===p.plot_type&&JSON.stringify(old.signal_bindings)===JSON.stringify(p.signal_bindings);});const otherUnchanged=otherBefore===JSON.stringify((await state(prod)).body.layouts.find(x=>x.display_id===originalActive.display.id));check("pane plot type change is isolated from siblings and other Display",siblingsUnchanged&&otherUnchanged,{before:beforeType.layout,after:afterType.layout});
   await clickDisplay(prod,originalActive.display.id);const linkTarget=activeLayout(await state(prod));const third=linkTarget.layout.panes[2];await prod.getByTestId(`pane-type-${third.id}`).selectOption("spectrum");await prod.waitForFunction(id=>document.querySelector(`[data-testid="pane-type-${id}"]`)?.value==="spectrum",third.id,{timeout:15000});await prod.getByTestId(`plot-pane-${linkTarget.layout.panes[0].id}`).click();await prod.getByTestId("time-settings-tab").click();const timeGroup=await prod.evaluate(()=>{const groups=[...document.querySelectorAll("[data-testid='settings-content'] .settings-group")];const link=[...document.querySelectorAll("[data-setting-id='time.link_time']")][0];return {titles:groups.map(g=>g.querySelector("[data-settings-group-toggle]")?.innerText.trim()),link:link&&{disabled:link.disabled,checked:link.checked,group:link.closest(".settings-group")?.dataset.settingsGroup}};});check("link time is visibly in Связь областей and eligibility matches sourced TIME panes",timeGroup.titles.includes("Связь областей")&&timeGroup.link?.group==="area-link"&&!timeGroup.link?.disabled,timeGroup);await shot(prod,"production-time-link-settings.png","time link eligibility");
   // A full linked-X proof needs two TIME panes. If the runtime exposes them, mutate only via visible controls and settings Apply; otherwise it remains explicitly not-run.
   const current=activeLayout(await state(prod));const timePanes=current.layout.panes.filter(p=>p.plot_type==="time"&&Array.isArray(p.signal_bindings)&&p.signal_bindings.length);
   if(timePanes.length>=2&&timeGroup.link&&!timeGroup.link.disabled){
     const link=prod.locator("[data-setting-id='time.link_time']"); if(!await link.isChecked())await link.check();
     const mins=prod.locator("[data-testid='settings-field-time.x_limits'] input[data-range-part='min']"), maxs=prod.locator("[data-testid='settings-field-time.x_limits'] input[data-range-part='max']");
     await mins.fill("0");await maxs.fill("0.001");
     const applyResp=prod.waitForResponse(r=>new URL(r.url()).pathname.endsWith("/api/settings/apply")&&r.request().method()==="POST",{timeout:30000});await prod.getByTestId("settings-apply").click();const ar=await applyResp;
     await prod.waitForFunction(async()=>{const r=await fetch("./api/state-lite",{cache:"no-store"});return r.ok;},null,{timeout:15000});
     const linked=activeLayout(await state(prod)); const reference=linked.layout.panes.find(q=>q.id===timePanes[0].id); const limit=reference&&(reference.settings?.["time.x_limits"]||reference.time_x_limits);
     const synced=linked.layout.panes.filter(p=>timePanes.some(t=>t.id===p.id)).every(p=>JSON.stringify(p.settings?.["time.x_limits"]||p.time_x_limits)===JSON.stringify(limit));
     check("linked valid X limits synchronize current Display TIME panes only",ar.ok()&&synced,{apply_status:ar.status(),layout:linked.layout});
   }else report.checks.push({name:"linked X limits synchronization",status:"not_run",detail:{reason:"current production state did not expose two sourced TIME panes",time_panes:timePanes,time_group:timeGroup}});
 } catch(e) { report.run_error=String(e&&e.stack||e);check("unhandled workflow error",false,{error:report.run_error}); }
 finally { if(prod&&!prod.isClosed()&&initial){ try { // Restore the initial active layout using visible dialog. Extra displays are closed only if created by this run.
     const wanted=activeLayout({body:initial}); const now=activeLayout(await state(prod)); if(wanted.display&&now.display&&wanted.display.id===now.display.id&&wanted.layout&&(now.layout.rows!==wanted.layout.rows||now.layout.columns!==wanted.layout.columns)) await setLayout(prod,wanted.layout.rows,wanted.layout.columns);
     report.restoration_attempt="partial: original active layout restored when still active; added Display and changed pane settings may remain";
   } catch(e){report.restoration_error=String(e);}}
   for(const p of tracked){if(!p.isClosed()){try{await p.close();report.closed_tab_count++;}catch(e){report.cleanup_error=String(e);}}} report.tab_cleanup_status=report.opened_tab_count===report.closed_tab_count&&!report.cleanup_error?"passed":"failed";
   const passed=report.checks.filter(x=>x.status==="passed").length,failed=report.checks.filter(x=>x.status==="failed").length,notRun=report.checks.filter(x=>x.status==="not_run").length; report.summary={planned:report.checks.length,passed,failed,not_run:notRun,success_rate:report.checks.length?+((passed/report.checks.length)*100).toFixed(1):0,availability:report.checks.find(x=>x.name==="availability and exact runtime revision")?.status||"failed"};report.summary.operational=report.summary.availability==="passed"&&report.summary.success_rate>=75&&!report.run_error;report.finished_at=new Date().toISOString();fs.writeFileSync(path.join(OUT,"report.json"),JSON.stringify(report,null,2));if(browser)await browser.close();console.log(JSON.stringify(report.summary)); }
}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
