"use strict";
const fs=require("fs"),path=require("path"),{chromium}=require("playwright-core"),{execFileSync}=require("child_process");
const target="https://engee.com/prod/user/demo54365638-bogoslm/genie/signal_analyser/";
const artifacts=path.resolve("test/playwright/artifacts/TASK-0086"),reportPath=path.join(artifacts,"settings-inventory.json");

async function state(page){return page.evaluate(async()=>{const response=await fetch("./api/state-lite",{headers:{Accept:"application/json","Cache-Control":"no-cache"},cache:"no-store"});const payload=await response.json();const entry=(payload.layouts||[]).find(item=>item.display_id===payload.active_display_id);const pane=entry&&entry.layout&&entry.layout.panes.find(item=>item.id===entry.layout.active_pane_id);return{revision:payload.state_revision,display:payload.active_display_id,pane:pane&&pane.id,plotType:pane&&pane.plot_type}})}
async function groups(page){return page.evaluate(()=>[...document.querySelectorAll("[data-testid='settings-content'] .settings-group")].map(section=>{const button=section.querySelector("[data-settings-group-toggle]"),body=section.querySelector(".settings-group-fields"),box=body.getBoundingClientRect();return{key:section.dataset.settingsGroup,title:button.innerText.trim(),expanded:button.getAttribute("aria-expanded"),focused:document.activeElement===button,hidden:body.hidden,bodyHeight:box.height,fields:[...section.querySelectorAll(".settings-label > span:first-child")].map(node=>node.textContent.trim())}}))}
async function setPlotType(page,type){for(let attempt=0;attempt<4;attempt+=1){const current=await state(page);if(current.plotType===type)return;const select=page.getByTestId("settings-field-display.plot_type").locator("select");await select.waitFor({state:"visible",timeout:15000});const responsePromise=page.waitForResponse(response=>response.url().endsWith("/api/layouts")&&response.request().method()==="POST",{timeout:15000});await select.selectOption(type);const response=await responsePromise;if(response.ok()){await page.waitForFunction(expected=>{const select=document.querySelector("[data-testid='settings-field-display.plot_type'] select");return select&&select.value===expected},type,{timeout:15000});await page.waitForFunction(async expected=>{const response=await fetch("./api/state-lite",{cache:"no-store"}),payload=await response.json(),entry=(payload.layouts||[]).find(item=>item.display_id===payload.active_display_id),pane=entry&&entry.layout&&entry.layout.panes.find(item=>item.id===entry.layout.active_pane_id);return pane&&pane.plot_type===expected},type,{timeout:15000});return}if(response.status()!==409)throw new Error(`layout HTTP ${response.status()}`);await page.waitForTimeout(350)}throw new Error(`could not select plot type ${type}`)}

(async()=>{fs.mkdirSync(artifacts,{recursive:true});const report={id:"HND-TASK-0086-SETTINGS-INVENTORY",target,revision:"136dbac17982fd1c59f902d4a46dd0f88561bc96",browser_channel:"chrome",headless:false,browser_visibility:"foreground",worker_count:1,checks:[],console:[],network:[],screenshots:[],opened:0,closed:0};const check=(name,pass,detail)=>report.checks.push({name,status:pass?"passed":"failed",detail});let browser,page,original;try{browser=await chromium.launch({channel:"chrome",headless:false});const context=browser.contexts()[0]||await browser.newContext();report.preexisting_pages=context.pages().map(item=>item.url());page=await context.newPage();report.opened=1;page.on("console",message=>{if(message.type()==="error")report.console.push({text:message.text(),url:message.location().url})});page.on("response",response=>{if(response.status()>=400||response.request().isNavigationRequest())report.network.push({status:response.status(),method:response.request().method(),url:response.url()})});await page.setViewportSize({width:1440,height:900});await page.bringToFront();try{execFileSync("osascript",["-e",'tell application "Google Chrome" to activate'])}catch(_){}await page.goto(target,{waitUntil:"domcontentloaded",timeout:60000});await page.getByTestId("app-shell").waitFor({state:"visible",timeout:60000});await page.locator("[data-settings-group-toggle]").first().waitFor({state:"visible",timeout:60000});original=await state(page);report.original=original;if(original.plotType!=="time")await setPlotType(page,"time");

await page.getByTestId("display-settings-tab").click();await page.waitForTimeout(100);let snapshot=await groups(page);check("Display/time repeats Graph subsection and fields",snapshot.length===1&&snapshot[0].title==="График"&&["Тип графика","Показывать легенду"].every(label=>snapshot[0].fields.includes(label)),snapshot);await page.screenshot({path:path.join(artifacts,"settings-display-time.png")});report.screenshots.push("settings-display-time.png");

let toggle=page.locator("[data-settings-group='graph'] [data-settings-group-toggle]");await toggle.click();await page.waitForFunction(()=>{const button=document.querySelector("[data-settings-group='graph'] [data-settings-group-toggle]"),body=document.querySelector("[data-settings-group='graph'] .settings-group-fields");return button&&button.getAttribute("aria-expanded")==="false"&&document.activeElement===button&&body.hidden});snapshot=await groups(page);check("Graph subsection collapses, hides body and retains focus",snapshot[0].expanded==="false"&&snapshot[0].hidden&&snapshot[0].bodyHeight===0&&snapshot[0].focused,snapshot[0]);await toggle.click();await page.waitForFunction(()=>document.querySelector("[data-settings-group='graph'] [data-settings-group-toggle]").getAttribute("aria-expanded")==="true");

await page.getByTestId("time-settings-tab").click();await page.waitForTimeout(100);snapshot=await groups(page);check("Time page repeats all designed subsections",JSON.stringify(snapshot.map(item=>item.title))===JSON.stringify(["Параметры","Пределы времени","Пределы оси Y","Связь экранов"]),snapshot);const expectedTime=["Нормировать Y","Показывать маркеры","Единицы времени","Пределы X","Пределы Y","Связать время"];check("Time page repeats all designed fields",expectedTime.every(label=>snapshot.some(group=>group.fields.includes(label))),snapshot);

toggle=page.locator("[data-settings-group='time-limits'] [data-settings-group-toggle]");await toggle.click();await page.waitForFunction(()=>document.querySelector("[data-settings-group='time-limits'] [data-settings-group-toggle]").getAttribute("aria-expanded")==="false");await page.getByTestId("statistics-settings-tab").click();await page.waitForTimeout(100);snapshot=await groups(page);check("Measurements repeats Statistics and Peaks subsections",JSON.stringify(snapshot.map(item=>item.title))===JSON.stringify(["Статистики","Пики"]),snapshot);const expectedMeasurements=["Минимум","Максимум","Среднее","Медиана","Размах","Среднеквадратичное","Искать пики"];check("Measurements repeats complete designed field inventory",expectedMeasurements.every(label=>snapshot.some(group=>group.fields.includes(label))),snapshot);await page.screenshot({path:path.join(artifacts,"settings-measurements.png")});report.screenshots.push("settings-measurements.png");

await page.getByTestId("statistics-settings-tab").press("ArrowLeft");let keyboard=await page.evaluate(()=>({selected:document.querySelector("[data-settings-page][aria-selected='true']").textContent.trim(),focused:document.activeElement&&document.activeElement.textContent.trim()}));check("settings tabs support roving keyboard selection and focus",keyboard.selected==="Время"&&keyboard.focused==="Время",keyboard);snapshot=await groups(page);const remembered=snapshot.find(item=>item.key==="time-limits");check("collapsed subsection state is independent and remembered",remembered&&remembered.expanded==="false"&&remembered.hidden,remembered);

await page.getByTestId("display-settings-tab").click();await setPlotType(page,"spectrum");await page.waitForFunction(()=>document.querySelectorAll("[data-settings-group]").length>=3,null,{timeout:15000});snapshot=await groups(page);check("Spectrum rebuilds exact designed subsections",JSON.stringify(snapshot.map(item=>item.title))===JSON.stringify(["График","Частотная ось","Спектральный анализ"]),snapshot);const spectrumFields=["Тип графика","Показывать легенду","Единицы частоты","Пределы частоты","Шкала частоты","Пределы Y","Спектр в dB","Тип разрешения","Утечка","Частотное разрешение"];check("Spectrum exposes full authoritative designed inventory",spectrumFields.every(label=>snapshot.some(group=>group.fields.includes(label))),snapshot);const localizedOptions=await page.evaluate(()=>[...document.querySelectorAll("[data-testid='settings-content'] option")].map(option=>option.textContent.trim()));check("settings enum options use design localization",localizedOptions.includes("Линейная")&&localizedOptions.includes("Логарифмическая")&&localizedOptions.includes("По утечке")&&localizedOptions.includes("По RBW")&&localizedOptions.includes("По длине окна"),localizedOptions);const chrome=await page.evaluate(()=>({settings:document.querySelectorAll("[data-testid='settings-panel']").length,content:document.querySelectorAll("[data-testid='settings-content']").length,footer:document.querySelectorAll("[data-testid='settings-footer']").length,apply:document.querySelectorAll("[data-testid='settings-apply']").length,objectObject:document.body.innerText.includes("[object Object]"),controls:[...document.querySelectorAll("[data-testid='settings-content'] input:not([type='checkbox']),[data-testid='settings-content'] select")].filter(node=>{const box=node.getBoundingClientRect();return box.width>0&&box.height>0}).map(node=>node.getBoundingClientRect().height)}));check("single settings subtree keeps canonical controls",chrome.settings===1&&chrome.content===1&&chrome.footer===1&&chrome.apply===1&&!chrome.objectObject&&chrome.controls.length>0&&chrome.controls.every(height=>Math.abs(height-32)<=1),chrome);await page.screenshot({path:path.join(artifacts,"settings-spectrum.png")});report.screenshots.push("settings-spectrum.png");

await setPlotType(page,"spectrogram");await page.getByTestId("settings-field-spectrogram.actual_rbw").waitFor({state:"attached",timeout:15000});snapshot=await groups(page);check("Spectrogram rebuilds exact designed subsections",JSON.stringify(snapshot.map(item=>item.title))===JSON.stringify(["График","Частотная ось","Мощность"]),snapshot);const spectrogramFields=["Тип графика","Показывать легенду","Единицы времени","Единицы частоты","Пределы частоты","Шкала частоты","Пределы мощности","Спектр в dB","Утечка","Разрешение по времени","Перекрытие","Переназначение","Фактическая RBW"];check("Spectrogram exposes full authoritative designed inventory",spectrogramFields.every(label=>snapshot.some(group=>group.fields.includes(label))),snapshot);await page.getByTestId("time-settings-tab").click();snapshot=await groups(page);check("Spectrogram Time page exposes only designed time limits",snapshot.length===1&&snapshot[0].title==="Пределы времени"&&JSON.stringify(snapshot[0].fields)===JSON.stringify(["Пределы X"]),snapshot);await page.getByTestId("display-settings-tab").click();await page.screenshot({path:path.join(artifacts,"settings-spectrogram.png")});report.screenshots.push("settings-spectrogram.png");

await setPlotType(page,"persistence");await page.getByTestId("settings-field-persistence.rbw").waitFor({state:"attached",timeout:15000});snapshot=await groups(page);check("Persistence rebuilds exact designed subsections",JSON.stringify(snapshot.map(item=>item.title))===JSON.stringify(["График","Частотная ось","Плотность и мощность"]),snapshot);const persistenceFields=["Тип графика","Показывать легенду","Единицы времени","Единицы частоты","Пределы частоты","Шкала частоты","Пределы мощности","Пределы плотности","Спектр в dB","Утечка","Разрешение по времени","Перекрытие","Интервалы мощности","RBW"];check("Persistence exposes full authoritative designed inventory",persistenceFields.every(label=>snapshot.some(group=>group.fields.includes(label))),snapshot);await page.getByTestId("time-settings-tab").click();snapshot=await groups(page);check("Persistence Time page renders designed not-applicable subsection",snapshot.length===1&&snapshot[0].title==="Временные настройки"&&snapshot[0].fields.includes("Применимость"),snapshot);await page.getByTestId("display-settings-tab").click();await page.screenshot({path:path.join(artifacts,"settings-persistence.png")});report.screenshots.push("settings-persistence.png");
}catch(error){report.error=String(error&&error.stack||error)}finally{if(page&&!page.isClosed()&&original){try{await page.getByTestId("display-settings-tab").click().catch(()=>{});await setPlotType(page,original.plotType);report.restored=await state(page);report.restore_ok=report.restored.plotType===original.plotType&&report.restored.display===original.display&&report.restored.pane===original.pane}catch(error){report.restore_error=String(error&&error.stack||error)}}if(page&&!page.isClosed()){await page.close();report.closed=1}report.tab_cleanup_status=report.opened===report.closed?"passed":"failed";const passed=report.checks.filter(item=>item.status==="passed").length,failed=report.checks.filter(item=>item.status==="failed").length;report.summary={planned:18,passed,failed,not_run:18-report.checks.length};fs.writeFileSync(reportPath,JSON.stringify(report,null,2));if(browser)await browser.close();process.stdout.write(`${JSON.stringify(report.summary)}\n`)}})();
