"use strict";
// TASK-0088 production evidence: visible-Chrome reproduction of the detached
// layout-segment event target, followed by UI-only removal of E2E-created tabs.
const fs=require("fs"),path=require("path"),assert=require("assert");
const {execFileSync}=require("child_process");
const {chromium}=require("playwright-core");
const target="https://engee.com/prod/user/demo54365638-bogoslm/genie/signal_analyser/";
const out=path.resolve("test/playwright/artifacts/TASK-0088"); fs.mkdirSync(out,{recursive:true});
const report={id:"HND-TASK-0088-E2E-LAYOUT-REPRO",type:"report",from:"E2E",to:"Orchestrator",target,browser_channel:"chrome",headless:false,browser_visibility:"foreground",worker_count:1,opened_tab_count:0,closed_tab_count:0,tab_cleanup_status:"pending",network:[],started_at:new Date().toISOString()};
async function front(page){await page.bringToFront();try{execFileSync("osascript",["-e",'tell application "Google Chrome" to activate']);report.chrome_activation="ok";}catch(e){report.chrome_activation_error=String(e);}}
async function snapshot(page,file){await front(page);await page.screenshot({path:path.join(out,file),fullPage:false});}
async function getState(page){return page.evaluate(async()=>{const r=await fetch("./api/state-lite",{cache:"no-store"});return {status:r.status,body:await r.json()};});}
async function closeDisplay(page,id){const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith("/api/displays")&&r.request().method()==="POST",{timeout:30000});await page.getByTestId(`display-close-${id}`).click();const r=await response;assert.equal(r.status(),200,`close ${id} status`);await page.waitForFunction(expected=>!document.querySelector(`[data-testid="display-tab-${expected}"]`),id,{timeout:15000});}
(async()=>{let browser,page;try{browser=await chromium.launch({channel:"chrome",headless:false});const context=browser.contexts()[0]||await browser.newContext({viewport:{width:1440,height:900}});report.preexisting_page_count=context.pages().length;page=await context.newPage();report.opened_tab_count++;page.on("response",r=>{if(/\/api\/(layouts|displays|state-lite)/.test(r.url()))report.network.push({status:r.status(),method:r.request().method(),url:r.url()});});await page.setViewportSize({width:1440,height:900});await front(page);const main=await page.goto(target,{waitUntil:"domcontentloaded",timeout:60000});report.main_document={status:main.status(),url:page.url()};await page.getByTestId("app-shell").waitFor({state:"visible",timeout:60000});await page.getByTestId("layout-trigger").click();const popover=page.getByTestId("layout-popover");await popover.waitFor({state:"visible"});const pre=await page.evaluate(()=>{const p=document.querySelector("[data-testid='layout-popover']"),b=document.querySelector("button[data-layout-columns='2']");return {popover_hidden:p.hidden,button_connected:b.isConnected,button_visible:!!(b.offsetWidth||b.offsetHeight||b.getClientRects().length),button_rect:b.getBoundingClientRect().toJSON(),active:document.activeElement&&document.activeElement.outerHTML.slice(0,300)};});await snapshot(page,"production-layout-segment-before.png");await page.locator("button[data-layout-columns='2']").click();await page.waitForFunction(()=>document.querySelector("[data-testid='layout-popover']").hidden,{timeout:5000});const post=await page.evaluate(()=>{const p=document.querySelector("[data-testid='layout-popover']"),b=document.querySelector("button[data-layout-columns='2']");return {popover_hidden:p.hidden,current_button_connected:b.isConnected,current_button_visible:!!(b.offsetWidth||b.offsetHeight||b.getClientRects().length),current_button_rect:b.getBoundingClientRect().toJSON(),active:document.activeElement&&document.activeElement.outerHTML.slice(0,300)};});await snapshot(page,"production-layout-segment-after.png");report.repro={action:"open layout dialog then click Columns 2",before:pre,after:post,observed:"popover closes immediately; layout is not applied"};assert.equal(pre.popover_hidden,false);assert.equal(pre.button_visible,true);assert.equal(post.popover_hidden,true);
let state=await getState(page);report.displays_before_cleanup=state.body.displays.map(d=>d.id);for(const d of state.body.displays.filter(d=>d.id!=="display-1")){await front(page);await closeDisplay(page,d.id);}state=await getState(page);report.displays_after_cleanup=state.body.displays.map(d=>d.id);report.cleanup_verified=state.body.displays.length===1&&state.body.displays[0].id==="display-1";assert.equal(report.cleanup_verified,true,"UI cleanup restores only Display 1");await snapshot(page,"production-after-ui-cleanup.png");}catch(e){report.error=String(e.stack||e);}finally{if(page&&!page.isClosed()){try{await page.close();report.closed_tab_count++;}catch(e){report.cleanup_error=String(e);}}report.tab_cleanup_status=report.opened_tab_count===report.closed_tab_count&&!report.cleanup_error?"passed":"failed";report.finished_at=new Date().toISOString();fs.writeFileSync(path.join(out,"layout-repro-report.json"),JSON.stringify(report,null,2));if(browser)await browser.close();console.log(JSON.stringify({error:report.error,repro:report.repro,cleanup:report.cleanup_verified,tabs:report.tab_cleanup_status}));}})();
