"use strict";
const fs = require("fs"), path = require("path");
const { execFileSync } = require("child_process");
const { chromium } = require("playwright-core");
const target = "https://engee.com/prod/user/demo54365638-bogoslm/genie/signal_analyser/";
const revision = "568a29f48edbfb2bb5f8ad3eaeea089c34a910ea";
const out = path.resolve("test/playwright/artifacts/TASK-0088"); fs.mkdirSync(out,{recursive:true});
const report={id:"HND-TASK-0088-E2E-POSTFIX-RESUME",type:"report",from:"E2E",to:"Orchestrator",target,expected_revision:revision,browser_channel:"chrome",headless:false,browser_visibility:"foreground",worker_count:1,checks:[],screenshots:[],api:[],errors:[],opened_tab_count:0,closed_tab_count:0,tab_cleanup_status:"pending",started_at:new Date().toISOString()};
const check=(name,pass,detail={})=>report.checks.push({name,status:pass?"passed":"failed",detail});
async function front(p){await p.bringToFront();try{execFileSync("osascript",["-e",'tell application "Google Chrome" to activate']);}catch(e){report.errors.push("chrome activate: "+e);}}
async function shot(p,file,state){await front(p);await p.screenshot({path:path.join(out,file),fullPage:false});report.screenshots.push({file,state,viewport:p.viewportSize(),time:new Date().toISOString()});}
async function state(p){const v=await p.evaluate(async()=>{const r=await fetch("./api/state-lite",{cache:"no-store"});return {status:r.status,body:await r.json()};});report.api.push({path:"/api/state-lite",status:v.status,active:v.body.active_display_id,layouts:(v.body.layouts||[]).map(x=>({display_id:x.display_id,layout:x.layout,outputs:(x.outputs||[]).map(o=>({pane_id:o.pane_id,plot_type:o.plot_type,bindings:o.signal_bindings,ready:o.isready,success:o.success,data_length:Array.isArray(o.output?.data)?o.output.data.length:null}))}))});return v.body;}
function layout(s,id=s.active_display_id){return s.layouts.find(x=>x.display_id===id)?.layout;}
function entry(s,id=s.active_display_id){return s.layouts.find(x=>x.display_id===id);}
async function openLayout(p){const pop=p.getByTestId("layout-popover");if(!await pop.isVisible())await p.getByTestId("layout-trigger").click();await pop.waitFor({state:"visible",timeout:15000});return pop;}
async function applyLayout(p,r,c,proof=false){const pop=await openLayout(p);for(const [axis,n] of [["rows",r],["columns",c]]){const b=p.locator(`button[data-layout-${axis}="${n}"]`);if(await b.getAttribute("aria-pressed")!=="true")await b.click();}
 if(proof){const visible=await pop.isVisible(),enabled=await p.getByTestId("layout-apply").isEnabled();check("Rows/Columns segment stays open and Apply is enabled",visible&&enabled,{visible,enabled,rows:r,columns:c});await shot(p,"postfix-layout-segment-open.png",`dialog after selecting ${r}x${c}`);}
 const response=p.waitForResponse(x=>new URL(x.url()).pathname.endsWith("/api/layouts")&&x.request().method()==="POST",{timeout:30000});await p.getByTestId("layout-apply").click();const x=await response;check(`Apply layout ${r}x${c} returns 200`,x.status()===200,{status:x.status()});await pop.waitFor({state:"hidden",timeout:15000});}
async function waitPlots(p,count){await p.waitForFunction(expected=>{const panes=[...document.querySelectorAll("[data-testid^='plot-pane-']")].filter(x=>x.getBoundingClientRect().width>0&&x.getBoundingClientRect().height>0);return panes.length===expected&&panes.every(x=>{const h=x.querySelector(".js-plotly-plot");return h&&Array.isArray(h.data)&&h.data.length>0;});},count,{timeout:60000});return p.evaluate(()=>[...document.querySelectorAll("[data-testid^='plot-pane-']")].map(x=>{const h=x.querySelector(".js-plotly-plot");return {pane:x.dataset.paneId||x.dataset.testid,traces:h?.data?.length||0,ready:x.querySelector("[data-plot-ready]")?.dataset.plotReady||null};}));}
async function clickDisplay(p,id){await p.getByTestId(`display-tab-${id}`).click();await p.waitForFunction(x=>document.querySelector("[data-testid='display-tab-"+x+"']")?.closest(".display-tab-shell")?.classList.contains("is-selected"),id,{timeout:15000});}
async function addDisplay(p){const before=(await state(p)).displays.length;const res=p.waitForResponse(x=>new URL(x.url()).pathname.endsWith("/api/displays")&&x.request().method()==="POST",{timeout:30000});await p.getByTestId("add-display").click();const x=await res;check("Add Display returns 200",x.status()===200,{status:x.status()});await p.waitForFunction(n=>document.querySelectorAll("[data-testid^='display-tab-']").length===n,before+1,{timeout:15000});return state(p);}
async function closeDisplay(p,id){const r=p.waitForResponse(x=>new URL(x.url()).pathname.endsWith("/api/displays")&&x.request().method()==="POST",{timeout:30000});await p.getByTestId(`display-close-${id}`).click();const x=await r;check(`Close ${id} returns 200`,x.status()===200,{status:x.status()});await p.waitForFunction(x=>!document.querySelector("[data-testid='display-tab-"+x+"']"),id,{timeout:15000});}
async function reset(p){let s=await state(p);for(const d of s.displays.filter(d=>d.id!=="display-1"))await closeDisplay(p,d.id);s=await state(p);if(s.active_display_id!=="display-1")await clickDisplay(p,"display-1");if(layout(s).rows!==1||layout(s).columns!==1)await applyLayout(p,1,1);}
async function selectType(p,pane,type){await p.getByTestId(`plot-pane-${pane}`).click();const field=p.getByTestId("settings-field-display.plot_type").locator("select");const r=p.waitForResponse(x=>new URL(x.url()).pathname.endsWith("/api/layouts")&&x.request().method()==="POST",{timeout:30000});await field.selectOption(type);const x=await r;check(`Pane ${pane} type ${type} returns 200`,x.status()===200,{status:x.status()});}
async function timeApply(p,min,max){const minI=p.locator("[data-testid='settings-field-time.x_limits'] input[data-range-part='min']"),maxI=p.locator("[data-testid='settings-field-time.x_limits'] input[data-range-part='max']");await minI.fill(String(min));await maxI.fill(String(max));const r=p.waitForResponse(x=>new URL(x.url()).pathname.endsWith("/api/settings/apply")&&x.request().method()==="POST",{timeout:30000});await p.getByTestId("settings-apply").click();const x=await r;check(`Time Apply ${min}..${max} returns 200`,x.status()===200,{status:x.status()});}
(async()=>{let browser,page;try{browser=await chromium.launch({channel:"chrome",headless:false});const c=browser.contexts()[0]||await browser.newContext({viewport:{width:1440,height:900}});report.preexisting_page_count=c.pages().length;page=await c.newPage();report.opened_tab_count++;await page.setViewportSize({width:1440,height:900});await front(page);const main=await page.goto(target,{waitUntil:"domcontentloaded",timeout:60000});report.main_document={status:main?.status(),url:page.url()};await page.getByTestId("app-shell").waitFor({state:"visible",timeout:60000});const status=await page.evaluate(async()=>{const r=await fetch("./api/status",{cache:"no-store"});return {status:r.status,body:await r.json()};});check("availability and exact production revision",status.status===200&&status.body.ready&&status.body.runtime_revision===revision,status);if(status.body.runtime_revision!==revision)throw Error("wrong runtime revision");
 await reset(page);await applyLayout(page,1,2,true);const plots=await waitPlots(page,2);const s1=await state(page),l1=layout(s1);check("1x2 contains two sourced non-empty Plotly graphs",plots.length===2&&plots.every(x=>x.traces>0)&&l1.panes.length===2&&entry(s1).outputs.every(x=>x.signal_bindings?.length&&x.success),{plots,panes:l1.panes,outputs:entry(s1).outputs});await shot(page,"postfix-1x2-ready.png","Display 1 1x2 non-empty Plotly");
 const afterAdd=await addDisplay(page),d2=afterAdd.displays.find(x=>x.id!=="display-1")?.id; if(!d2)throw Error("Display 2 not created");await applyLayout(page,2,1);await waitPlots(page,2);const d2Layout=layout(await state(page),d2);await clickDisplay(page,"display-1");const d1Layout=layout(await state(page));check("Displays retain distinct layouts after switching",d1Layout.rows===1&&d1Layout.columns===2&&d2Layout.rows===2&&d2Layout.columns===1,{display1:d1Layout,display2:d2Layout});
 await clickDisplay(page,d2);const before=await state(page),pane=layout(before).active_pane_id,other=layout(before).panes.find(x=>x.id!==pane);await selectType(page,pane,"spectrum");const after=await state(page),sameOther=JSON.stringify(layout(after).panes.find(x=>x.id===other.id))===JSON.stringify(other),d1Same=JSON.stringify(entry(after,"display-1"))===JSON.stringify(entry(before,"display-1"));check("Pane type mutation is local to selected pane and Display",sameOther&&d1Same,{active:pane,other:other.id});
 await clickDisplay(page,"display-1");await applyLayout(page,1,3);await waitPlots(page,3);let ts=await state(page),tl=layout(ts),third=tl.panes[2].id;await selectType(page,third,"spectrum");await page.getByTestId(`plot-pane-${tl.panes[0].id}`).click();await page.getByTestId("time-settings-tab").click();const link=page.locator("[data-setting-id='time.link_time']");const group=await link.evaluate(x=>({disabled:x.disabled,group:x.closest(".settings-group")?.dataset.settingsGroup,title:x.closest(".settings-group")?.querySelector("[data-settings-group-toggle]")?.textContent.trim()}));check("Связь областей is enabled for two sourced TIME panes",!group.disabled&&group.group==="area-link"&&group.title==="Связь областей",group);if(!await link.isChecked())await link.check();await timeApply(page,0.02,0.06);const linked=await state(page),linkedTime=layout(linked).panes.filter(x=>x.plot_type==="time"),spectrum=layout(linked).panes.find(x=>x.plot_type==="spectrum"),otherDisplay=entry(linked,d2);const timeSettings=await Promise.all(linkedTime.map(async x=>page.evaluate(async id=>{const r=await fetch("./api/settings?display_id=display-1&pane_id="+id,{cache:"no-store"});return {id,status:r.status,body:await r.json()};},x.id)));report.time_settings_after_link=timeSettings;const serial=JSON.stringify(timeSettings.map(x=>x.body.values?.["time.x_limits"]||x.body.settings?.["time.x_limits"]));check("linked X limits synchronize only same Display TIME panes",new Set(timeSettings.map(x=>JSON.stringify(x.body.values?.["time.x_limits"]||x.body.settings?.["time.x_limits"]))).size===1&&spectrum.plot_type==="spectrum"&&JSON.stringify(entry(await state(page),d2))===JSON.stringify(otherDisplay),{linkedTime:linkedTime.map(x=>x.id),spectrum:spectrum.id,timeSettings});if(await link.isChecked())await link.uncheck();await timeApply(page,0.08,0.12);const unlinked=await Promise.all(linkedTime.map(async x=>page.evaluate(async id=>{const r=await fetch("./api/settings?display_id=display-1&pane_id="+id,{cache:"no-store"});return {id,body:await r.json()};},x.id)));check("unlink returns X limits to pane-local behavior",JSON.stringify(unlinked[0].body.values?.["time.x_limits"]||unlinked[0].body.settings?.["time.x_limits"])!==JSON.stringify(unlinked[1].body.values?.["time.x_limits"]||unlinked[1].body.settings?.["time.x_limits"]),{unlinked});
 }catch(e){report.errors.push(String(e&&e.stack||e));check("workflow completed without unhandled error",false,{error:report.errors.at(-1)});}finally{if(page&&!page.isClosed()){try{await reset(page);await page.getByTestId("time-settings-tab").click().catch(()=>{});const min=page.locator("[data-testid='settings-field-time.x_limits'] input[data-range-part='min']"),max=page.locator("[data-testid='settings-field-time.x_limits'] input[data-range-part='max']");if(await min.count())await timeApply(page,0,0.24951171875);const final=await state(page);report.final_state={displays:final.displays.map(x=>x.id),active:final.active_display_id,layout:layout(final)};check("visible UI cleanup leaves Display 1 at 1x1",final.displays.length===1&&final.active_display_id==="display-1"&&layout(final).rows===1&&layout(final).columns===1,report.final_state);}catch(e){report.errors.push("cleanup: "+e);}
 try{await page.close();report.closed_tab_count++;}catch(e){report.errors.push("tab close: "+e);}}report.tab_cleanup_status=report.opened_tab_count===report.closed_tab_count?"passed":"failed";report.finished_at=new Date().toISOString();const p=report.checks.filter(x=>x.status==="passed").length,f=report.checks.filter(x=>x.status==="failed").length;report.summary={planned:report.checks.length,passed:p,failed:f,success_rate:+(100*p/report.checks.length).toFixed(1)};fs.writeFileSync(path.join(out,"postfix-resume-report.json"),JSON.stringify(report,null,2));if(browser)await browser.close();console.log(JSON.stringify(report.summary));}})();
