"use strict";
// Foreground, non-mutating v21 .sazip regression.  It intentionally stops before Import commit.
const fs = require("fs"), path = require("path"), { execFileSync } = require("child_process");
const { chromium } = require("playwright-core");
const target = "https://engee.com/prod/user/demo54365638-bogoslm/genie/signal_analyser/";
const revision = "94b7c8a6af8b883db9d78cd2f0f4767e138f2091";
const prototype = "file:///Users/makar/work/Genie_Tests/SignalAnalyser/architecture/design/TASK-0104-engee-portable-session-package/prototype/index.html";
const outDir = path.resolve(__dirname, "artifacts/TASK-0104-V21-QUICK"); fs.mkdirSync(outDir, { recursive: true });
const report = { id:"HND-TASK-0104-V21-E2E", type:"report", from:"E2E", to:"Orchestrator", e2e_mode:"new_functionality_regression", target, expected_revision:revision, design_ref:"architecture/design/TASK-0104-engee-portable-session-package/DESIGN.md", design_version:21, applied_skills:["e2e/e2e-workflow","e2e/visual-analysis"], browser_channel:"chrome", headless:false, browser_visibility:"foreground", worker_count:1, checks:[], screenshots:[], network:[], errors:[], opened_tab_count:0, closed_tab_count:0 };
const check=(name, ok, detail={})=>report.checks.push({name,status:ok?"passed":"failed",detail});
const shot=async(p,n)=>{const f=path.join(outDir,n);await p.screenshot({path:f,fullPage:true});report.screenshots.push(f);};
const front=async p=>{await p.bringToFront();try{execFileSync("osascript",["-e",'tell application "Google Chrome" to activate']);}catch(_){} };
const textOf=async l=>(await l.allTextContents()).map(x=>x.trim()).join("\n");
(async()=>{let browser,context,design,prod,downloadPath; const tracked=[]; try {
  browser=await chromium.launch({channel:"chrome",headless:false}); context=browser.contexts()[0]||await browser.newContext({acceptDownloads:true}); report.preexisting_pages=context.pages().map(p=>p.url());
  design=await context.newPage(); tracked.push(design); report.opened_tab_count++; await front(design); await design.setViewportSize({width:1024,height:768}); await design.goto(prototype,{waitUntil:"load",timeout:30000});
  const save=design.locator("[data-design-id=toolbar-save]"); await save.focus(); await save.click(); await design.locator("[data-design-id=save-content-list]").waitFor({state:"visible"});
  const rows=design.locator("[data-design-id=save-content-list] > *"); const inputs=design.locator("[data-design-id=save-content-list] input");
  check("prototype Save: exactly five fixed included rows",await rows.count()===5&&await inputs.count()===0,{rows:await rows.count(),inputs:await inputs.count()}); await shot(design,"prototype-save.png");
  await design.locator("[data-design-id=save-create]").click(); await design.locator("[data-design-id=save-error]").waitFor({state:"visible",timeout:15000}); await design.locator("[data-design-id=save-retry]").click(); await design.locator("[data-design-id=save-ready]").waitFor({state:"visible",timeout:15000}); await design.locator("[data-design-id=save-download]").click(); await design.keyboard.press("Escape");
  await design.locator("[data-design-id=toolbar-import]").click(); await design.locator("[data-design-id=prototype-file-picker]").waitFor({state:"visible"}); await design.locator("[data-design-id=prototype-file-picker]").getByText(/valid/i).first().click(); await design.locator("[data-design-id=import-validate]").click(); await design.locator("[data-design-id=import-summary]").waitFor({state:"visible",timeout:15000});
  const summary=await textOf(design.locator("[data-design-id=import-summary]")); const pub=design.locator("[data-design-id=workspace-publish]"); check("prototype valid summary, safe-script copy, workspace opt-in default",/sazip v1/i.test(summary)&&/никогда не выполняется|не будет выполнен/i.test(summary)&&!(await pub.isChecked()),{summary:summary.slice(0,800)}); await pub.check(); check("prototype opt-in reveals prefix and collision warning",await design.locator("[data-design-id=workspace-prefix]").isVisible()&&await design.locator("[data-design-id=workspace-collision-warning]").isVisible()); await shot(design,"prototype-import-summary-optin.png");
  prod=await context.newPage(); tracked.push(prod); report.opened_tab_count++; await front(prod); await prod.setViewportSize({width:1024,height:768}); prod.on("response",r=>{if(/\/api\/(status|session\/package)/.test(r.url()))report.network.push({method:r.request().method(),url:r.url(),status:r.status(),headers:r.headers()});}); const nav=await prod.goto(target,{waitUntil:"domcontentloaded",timeout:120000}); await prod.getByTestId("app-shell").waitFor({state:"visible",timeout:180000}); const st=await prod.evaluate(async()=>{const r=await fetch("./api/status",{cache:"no-store"});return{status:r.status,body:await r.json()};}); check("availability and exact runtime revision",nav&&nav.status()===200&&st.status===200&&st.body.ready===true&&st.body.runtime_revision===revision,{nav:nav&&nav.status(),status:st}); if(!(st.body.ready&&st.body.runtime_revision===revision))throw Error("revision gate failed: "+JSON.stringify(st));
  await front(prod); const saveButton=prod.getByRole("button",{name:"Сохранить пакет"}).first(); await saveButton.click(); const dialog=prod.getByRole("dialog"); await dialog.waitFor({state:"visible",timeout:30000}); const saveText=await textOf(dialog); const five=["Сессия и настройки","Исходные данные сигналов","Снимки готовых графиков","reproduce.jl","Метаданные зависимостей"]; check("production Save v21 fixed five rows and script-never-exec copy",five.every(x=>saveText.includes(x))&&/никогда не запускается автоматически/i.test(saveText),{text:saveText.slice(0,1600)}); await shot(prod,"production-save.png");
  const responsePromise=prod.waitForResponse(r=>new URL(r.url()).pathname.endsWith("/api/session/package")&&r.request().method()==="GET",{timeout:60000}); const downloadPromise=prod.waitForEvent("download",{timeout:60000}); await dialog.getByRole("button",{name:"Сохранить пакет"}).click(); const [res,download]=await Promise.all([responsePromise,downloadPromise]); const headers=res.headers(); downloadPath=await download.path(); const pk=downloadPath?fs.readFileSync(downloadPath).subarray(0,2).toString("hex"):""; check("GET /api/session/package has downloadable .sazip PK bytes",res.status()===200&&/attachment/i.test(headers["content-disposition"]||"")&&/sazip/i.test(headers["content-disposition"]||"")&&/application\/(zip|octet-stream)/i.test(headers["content-type"]||"")&&pk==="504b",{status:res.status(),contentType:headers["content-type"],contentDisposition:headers["content-disposition"],pk,downloadPath:!!downloadPath}); await prod.getByRole("button",{name:"Закрыть"}).click();
  await front(prod); const importButton=prod.getByRole("button",{name:"Импортировать пакет"}).first(); const chooser=prod.waitForEvent("filechooser",{timeout:30000}); await importButton.click(); const fc=await chooser; check("Import native chooser accepts only .sazip",String(await fc.element().getAttribute("accept")||"").includes(".sazip"),{accept:await fc.element().getAttribute("accept")}); if(downloadPath){await fc.setFiles(downloadPath); await prod.getByRole("dialog").waitFor({state:"visible",timeout:30000}); const importDialog=prod.getByRole("dialog"); const copy=await textOf(importDialog); check("selected-file dialog has safe-script warning",/никогда не выполняется|никогда не запускается/i.test(copy),{copy:copy.slice(0,900)}); const validateResponse=prod.waitForResponse(r=>/\/api\/session\/.+/.test(new URL(r.url()).pathname)&&r.request().method()!=="GET",{timeout:60000}).catch(()=>null); await importDialog.getByRole("button",{name:"Проверить пакет"}).click(); await prod.getByText("Пакет проверен").waitFor({state:"visible",timeout:60000}); const s=await textOf(importDialog); const workspace=importDialog.getByLabel("Опубликовать сигналы в рабочую область Engee"); check("valid package summary: v1, safe-script, workspace default off",/sazip v1/i.test(s)&&/не будет выполнен|никогда не выполняется/i.test(s)&&!(await workspace.isChecked()),{summary:s.slice(0,1500)}); await workspace.check(); check("workspace opt-in conditionally reveals prefix and collision UI",await importDialog.getByLabel("Префикс имён").isVisible()&&/совпадени/i.test(await textOf(importDialog)),{}); await shot(prod,"production-import-validated-optin.png"); await validateResponse; await importDialog.getByRole("button",{name:"Отмена"}).click(); } else check("import validation using downloaded package",false,{reason:"download path unavailable"});
 } catch(e){report.errors.push(String(e&&e.stack||e));} finally { for(const p of tracked){if(!p.isClosed())try{await p.close();report.closed_tab_count++;}catch(e){report.errors.push("cleanup: "+e);}} report.tab_cleanup_status=report.opened_tab_count===report.closed_tab_count?"passed":"failed"; report.planned=report.checks.length; report.passed=report.checks.filter(x=>x.status==="passed").length; report.failed=report.checks.filter(x=>x.status==="failed").length; report.success_rate=report.planned?Math.round(report.passed/report.planned*100):0; fs.writeFileSync(path.join(outDir,"report.json"),JSON.stringify(report,null,2)); if(browser)await browser.close(); console.log(JSON.stringify({planned:report.planned,passed:report.passed,failed:report.failed,success_rate:report.success_rate,errors:report.errors,cleanup:report.tab_cleanup_status},null,2)); if(report.errors.length||report.failed)process.exitCode=1; }
})();
