"use strict";

// DEC-039 integrated browser contract.  The published page/assets and its two
// initial GETs are real; every POST is fulfilled in-browser before the network.
const { openAppPage, testIdSelector, waitForAppReady } = require("../../support/app_page");
const { signalRowsState, waitForApi } = require("../../support/signal_analyser_page");
const TIMEOUT = 30000;
const CATALOG = "wc_00000000-0000-4000-8000-000000000000";
const RAW = "wv_raw", TIMED = "wv_timed", BAD = "wv_bad";
function id(p,c,n) { return p.locator(testIdSelector(c.app.testIds[n])); }
function clone(v) { return JSON.parse(JSON.stringify(v)); }
function state(p) { return p.evaluate(async () => await window.SignalAnalyserApi.getState()); }
function origin(p,c,a,label) { return p.evaluate(() => location.origin).then(o => a((c.app.allowedOrigins || []).includes(o), `${label}: forbidden redirect ${o}`)); }
function keys(a,b,k,label) { a(JSON.stringify(Object.keys(b).sort()) === JSON.stringify(k.slice().sort()), `${label}: exact keys required`); }
function snap(rev, names, selected) {
  const display={id:"display-e2e",name:"Display E2E",active_plot:"time",analysis_signal:selected,selected_signal:selected,visible_signals:names,time_limits:{min_s:0,max_s:.2,units:"s"},measurement_kinds:["minimum","maximum","mean"],peaks_enabled:false,spectrum_settings:{scale:"db",frequency_scale:"linear",leakage:.5,frequency_limits:null},spectrogram_settings:{overlap_percent:50,leakage:.5,frequency_limits:null,frequency_scale:"linear",power_limits:null},persistence_settings:{leakage:.5}};
  const tr=(n,i)=>({name:n,signal:n,x:[0,.1,.2],y:i?[1,0,1]:[0,1,0]});
  return {state_revision:rev,active_display_id:display.id,row_selected_signal:selected,analysis_signal:selected,selected_signal:selected,active_plot:"time",visible_signals:names,displays:[display],time_limits:clone(display.time_limits),signals:names.map((name,i)=>({name,color:i?"#dc2626":"#2563eb",sample_rate_hz:10,sample_count:3,duration_s:.2,data_type:"Вещественный",visible:true})),plots:{time:{type:"line",x:[0,.1,.2],y:[0,1,0],x_label:"Time",y_label:"Amplitude"}},plot_payload:{selected_signal:selected,visible_signals:names,time_traces:names.map(tr),spectrum_traces:names.map(tr),spectrogram:{type:"heatmap",signal:selected,x:[0,.1],y:[0,5],z:[[0,1],[1,0]],power_limits:{mode:"auto",requested:null,effective:null}},persistence:{type:"heatmap",signal:selected,x:[0,5],y:[-30,-10],z:[[1,2],[3,4]]}},panel:{fields:[]},measurements:{state_revision:rev,signal_name:selected,ordinate:"real",units:{value:"1",time:"s"},items:[]},peaks:{enabled:false,state_revision:rev,display_id:display.id,signal_name:selected,ordinate:"real",units:{value:"1",time:"s",width:"samples",prominence:"1"},items:[]}};
}
function catalog(revision=CATALOG,truncated=false) { return {catalog_revision:revision,expires_at:"2099-01-01T00:00:00Z",truncated,total:truncated?1001:3,variables:[{variable_id:RAW,name:"raw matrix",type:"Matrix{Float64}",shape:[3,2],sample_count:3,source_kind:"raw_matrix",compatibility:"requires_sample_rate",reason:null,sample_rate_requirement:"required",selectable:true},{variable_id:TIMED,name:"timed vector",type:"Timed",shape:[3],sample_count:3,source_kind:"timed_vector",compatibility:"compatible",reason:null,sample_rate_requirement:"not_needed",selectable:true},{variable_id:BAD,name:"unsupported",type:"String",shape:[],sample_count:0,source_kind:"unsupported",compatibility:"incompatible",reason:"Тип не поддерживается",sample_rate_requirement:"unsupported",selectable:false}]}; }
async function ready(p,c) { await waitForAppReady(p,c,{timeout:TIMEOUT}); await p.waitForFunction(s=>document.querySelector(s)?.getAttribute("aria-busy")!=="true",testIdSelector(c.app.testIds.shell),{timeout:TIMEOUT}); }

async function testSignalsInspectorActions({appUrl,assert,config,log,page,step,useCurrentPage}) {
  let current=snap(0,["E2E Tone","E2E Chirp"],"E2E Tone"), stateRoute, catalogRoute, viewRoute, signalsRoute, quarantine;
  let catalogMode="normal";
  const posts=[], signalWire=[]; const add=id(page,config,"signalsAddAction"), menu=id(page,config,"signalsAddMenu"), workspace=id(page,config,"signalsAddWorkspaceAction");
  const trace=[];
  try {
    await step("real read-only health then quarantined DEC-039 catalog seam",async()=>{
      quarantine=async r=>{if(r.request().method()!=="POST") return r.continue(); posts.push({url:r.request().url(),body:r.request().postData()||"",kind:"quarantine"}); await r.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:{message:"unexpected quarantined mutation"}})});};
      await page.route("**/api/**",quarantine); await openAppPage(page,{appUrl,config,log,useCurrentPage}); await origin(page,config,assert,"initial target"); await ready(page,config);
      const health=await state(page); assert(Number.isInteger(health.state_revision),"real GET /api/state health required");
      const realCatalog=await page.evaluate(async()=>await window.SignalAnalyserApi.workspaceVariables()); assert(typeof realCatalog.catalog_revision==="string","real GET /api/workspace/variables health required");
      stateRoute=async r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(current)});
      catalogRoute=async r=>{if(catalogMode==="error"){catalogMode="truncated";return r.fulfill({status:502,contentType:"application/json",body:JSON.stringify({error:{message:"catalog unavailable"}})});} return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(catalog(CATALOG,catalogMode==="truncated"))});};
      viewRoute=async r=>{const b=JSON.parse(r.request().postData()||"{}"); posts.push({url:r.request().url(),body:r.request().postData()||"",kind:"view"}); keys(assert,b,["state_revision","active_plot","row_selected_signal","analysis_signal","visible_signals","time_limits","measurement_kinds","spectrum_settings","spectrogram_settings","persistence_settings","peaks_enabled"],"view"); assert(b.state_revision===current.state_revision&&b.row_selected_signal==="E2E Tone"&&b.analysis_signal==="E2E Tone","view exact selection/revision"); assert(JSON.stringify(b.visible_signals)===JSON.stringify(b.state_revision===0?["E2E Tone"]:["E2E Tone","E2E Chirp"]),"view exact membership payload"); current=snap(current.state_revision+1,current.signals.map(x=>x.name),b.row_selected_signal); current.displays[0].visible_signals=b.visible_signals; current.visible_signals=b.visible_signals; trace.push({route:"view",revision:b.state_revision,response:current.state_revision,visible:b.visible_signals}); await r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(current)});};
      await page.route("**/api/state*",stateRoute); await page.route("**/api/workspace/variables*",catalogRoute); await page.route("**/api/view*",viewRoute);
      signalsRoute=async r=>{const b=JSON.parse(r.request().postData()||"{}"); posts.push({url:r.request().url(),body:r.request().postData()||"",kind:"signals"}); if(b.operation!=="import_workspace_batch"){const allowed=b.operation==="extract_time_limits"?["state_revision","operation","display_id"]:["state_revision","operation","signal_name"];keys(assert,b,allowed,b.operation);assert(b.state_revision===current.state_revision,"continuation pre-revision");let names=current.signals.map(x=>x.name), selected=current.row_selected_signal;if(b.operation==="duplicate"){assert(b.signal_name==="raw matrix","Copy target");selected=`${b.signal_name}_Copy`;names.push(selected);}else if(b.operation==="extract_time_limits"){assert(b.display_id==="display-e2e","extract active Display");selected=`${current.row_selected_signal}_Extract`;names.push(selected);}else if(b.operation==="delete"){assert(b.signal_name==="raw matrix_Copy_Extract","Delete target");names=names.filter(n=>n!==b.signal_name);selected=names[0];}current=snap(current.state_revision+1,names,selected);trace.push({route:b.operation,revision:b.state_revision,response:current.state_revision});return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(current)});} keys(assert,b,["state_revision","operation","catalog_revision","selections"],"batch"); assert(b.operation==="import_workspace_batch"&&b.catalog_revision===CATALOG&&b.state_revision===2,"batch operation/catalog/revision"); assert(JSON.stringify(b.selections)===JSON.stringify([{variable_id:RAW,sample_rate_hz:48000},{variable_id:TIMED,sample_rate_hz:null}]),"catalog-order opaque batch payload"); signalWire.push(b); if(signalWire.length===1){trace.push({route:"batch",revision:2,status:422});await r.fulfill({status:422,contentType:"application/json",body:JSON.stringify({error:{message:"synthetic 422"}})});return;} if(signalWire.length===2){trace.push({route:"batch",revision:2,status:409});await r.fulfill({status:409,contentType:"application/json",body:JSON.stringify({error:{code:"stale_state"},current})});return;} const names=current.signals.map(x=>x.name).concat(["raw matrix","timed vector"]); current=snap(current.state_revision+1,names,"raw matrix");trace.push({route:"batch",revision:2,status:200,response:3}); await r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(current)});}; await page.route("**/api/signals*",signalsRoute);
      await page.reload({waitUntil:"domcontentloaded"}); await origin(page,config,assert,"seam reload"); await ready(page,config);
    });
    await step("keyboard Add and workspace catalog selection",async()=>{
      const initialRows=await signalRowsState(page,config), selectedRow=initialRows.find(x=>x.selected), membershipRow=initialRows.find(x=>x.checked&&!x.selected); assert(selectedRow&&membershipRow,"fixture needs separate row selection and membership"); let membershipResponse=waitForApi(page,config,config.app.api.view,"POST"); await page.locator(testIdSelector(membershipRow.checkboxTestId)).setChecked(false); await membershipResponse; assert((await state(page)).row_selected_signal===selectedRow.name,"unchecking membership does not select another row"); membershipResponse=waitForApi(page,config,config.app.api.view,"POST"); await page.locator(testIdSelector(membershipRow.checkboxTestId)).setChecked(true); await membershipResponse; assert((await state(page)).state_revision===2,"restored membership establishes frozen pre-batch revision 2");
      await add.focus(); await add.press("Enter"); await menu.waitFor({state:"visible"}); await page.waitForFunction(x=>document.activeElement?.getAttribute("data-testid")===x,config.app.testIds.signalsAddWorkspaceAction); await workspace.click();
      const dialog=id(page,config,"signalsWorkspaceDialog"), list=id(page,config,"signalsWorkspaceList"); await dialog.waitFor({state:"visible"}); await list.waitFor(); assert(await page.locator(testIdSelector(`signals-workspace-select-${BAD}`)).isDisabled(),"incompatible catalog entry disabled"); assert((await list.innerText()).includes("Не поддерживается")&&(await list.innerText()).includes("Тип:"),"incompatible reason/metadata visible");
      await page.locator(testIdSelector(`signals-workspace-select-${TIMED}`)).setChecked(true); await page.locator(testIdSelector(`signals-workspace-select-${RAW}`)).setChecked(true); assert(!(await id(page,config,"signalsWorkspaceSampleRateGroup").isHidden())&&(await id(page,config,"signalsWorkspaceSubmit").isDisabled()),"raw+timed selection requires global Fs");
      const rate=id(page,config,"signalsWorkspaceSampleRateInput"); await rate.fill("48000"); assert(!(await id(page,config,"signalsWorkspaceSubmit").isDisabled()),"valid global Fs enables batch");
      const close=id(page,config,"signalsWorkspaceClose"), submit=id(page,config,"signalsWorkspaceSubmit"); await close.focus(); await page.keyboard.press("Shift+Tab"); await page.waitForFunction(x=>document.activeElement?.getAttribute("data-testid")===x,config.app.testIds.signalsWorkspaceSubmit); await submit.focus(); await page.keyboard.press("Tab"); await page.waitForFunction(x=>document.activeElement?.getAttribute("data-testid")===x,config.app.testIds.signalsWorkspaceClose); await page.keyboard.press("Escape"); await page.keyboard.press("Enter"); await page.mouse.click(1,1); assert(await dialog.isVisible()&&(await id(page,config,"signalsWorkspaceSelectionCount").innerText()).includes("2"),"loaded catalog form wraps Tab/Shift+Tab and keeps Escape, Enter and overlay inert with selection");
      const before=(await signalRowsState(page,config)).length; const response=waitForApi(page,config,config.app.api.signals,"POST"); await id(page,config,"signalsWorkspaceSubmit").click(); assert((await signalRowsState(page,config)).length===before,"batch has no optimistic rows"); assert((await response).status()===422&&await id(page,config,"signalsWorkspaceBatchError").isVisible(),"422 preserves browser"); assert(await rate.inputValue()==="48000","422 preserves global Fs");
      const stale=waitForApi(page,config,config.app.api.signals,"POST"); await id(page,config,"signalsWorkspaceSubmit").click(); assert((await stale).status()===409,"first stale state response"); await page.waitForFunction(()=>document.querySelector("[data-testid='signals-workspace-success']")?.hidden===false,{timeout:TIMEOUT}); assert(signalWire.length===3,"future catalog stale_state retries exactly once");
      await id(page,config,"signalsWorkspaceSuccess").waitFor({state:"visible"}); assert((await id(page,config,"signalsWorkspaceSuccessCount").innerText()).includes("2"),"separate batch success count"); await page.keyboard.press("Escape"); assert(await id(page,config,"signalsWorkspaceSuccess").isVisible(),"success Escape inert"); await id(page,config,"signalsWorkspaceDone").click(); assert(await id(page,config,"signalsWorkspaceSuccess").isHidden(),"Done-only success dismisses");
    });
    await step("refresh/truncated and catalog conflict fail closed",async()=>{
      await add.click(); await workspace.click(); catalogMode="error"; await id(page,config,"signalsWorkspaceRefresh").click(); await id(page,config,"signalsWorkspaceRetry").waitFor({state:"visible"}); assert(await id(page,config,"signalsWorkspaceBatchError").isVisible(),"catalog error exposes Retry"); await id(page,config,"signalsWorkspaceRetry").click(); await id(page,config,"signalsWorkspaceList").waitFor(); assert((await id(page,config,"signalsWorkspaceSelectionCount").innerText()).includes("лимит 1000"),"truncated total notice visible after retry");
      // A catalog conflict never replays: route a temporary catalog response and assert no extra batch POST after 409 workspace_changed.
      await page.unroute("**/api/signals*",signalsRoute); let conflict=async r=>{const b=JSON.parse(r.request().postData()||"{}");posts.push({url:r.request().url(),body:r.request().postData()||"",kind:"signals"}); keys(assert,b,["state_revision","operation","catalog_revision","selections"],"workspace_changed");assert(b.state_revision===3&&b.catalog_revision===CATALOG&&JSON.stringify(b.selections)===JSON.stringify([{variable_id:RAW,sample_rate_hz:48000}]),"workspace_changed exact one-selection body at revision 3");trace.push({route:"conflict",revision:3,status:409}); await r.fulfill({status:409,contentType:"application/json",body:JSON.stringify({error:{code:"workspace_changed"}})});}; await page.route("**/api/signals*",conflict);
      await page.locator(testIdSelector(`signals-workspace-select-${RAW}`)).setChecked(true); await id(page,config,"signalsWorkspaceSampleRateInput").fill("48000"); await id(page,config,"signalsWorkspaceSubmit").click(); await page.waitForFunction(()=>document.querySelector("[data-testid='signals-workspace-submit']")?.disabled===true,{timeout:TIMEOUT}); assert((await id(page,config,"signalsWorkspaceSelectionCount").innerText()).includes("Каталог обновлён"),"catalog conflict fails closed without replay"); await page.unroute("**/api/signals*",conflict); await page.route("**/api/signals*",signalsRoute);
    });
    await step("copy extract delete continuation and zero escaped POST",async()=>{
      await id(page,config,"signalsWorkspaceCancel").click();
      let post=waitForApi(page,config,config.app.api.signals,"POST"); await id(page,config,"signalsCopyAction").click(); assert((await post).status()===200&&(await state(page)).row_selected_signal.endsWith("_Copy"),"Copy authoritative selection");
      await add.click(); post=waitForApi(page,config,config.app.api.signals,"POST"); await id(page,config,"signalsAddSelectionAction").click(); assert((await post).status()===200&&(await state(page)).row_selected_signal.endsWith("_Extract"),"selected Time Limits Extract");
      const target=(await state(page)).row_selected_signal; await id(page,config,"signalsDeleteAction").click(); await id(page,config,"signalsDeleteDialog").waitFor({state:"visible"}); await id(page,config,"signalsDeleteCancel").click(); assert((await state(page)).row_selected_signal===target,"Delete cancel preserves inventory"); await id(page,config,"signalsDeleteAction").click(); post=waitForApi(page,config,config.app.api.signals,"POST"); await id(page,config,"signalsDeleteConfirm").click(); assert((await post).status()===200,"Delete confirm request"); await id(page,config,"signalsDeleteDone").waitFor({state:"visible"}); await page.keyboard.press("Tab"); assert(await id(page,config,"signalsDeleteDone").isVisible(),"acknowledged Done focus trap"); await id(page,config,"signalsDeleteDone").click(); assert(!(await state(page)).signals.some(x=>x.name===target),"final authoritative delete inventory");
      assert(posts.every(x=>x.url.includes("/api/")),"every mutation request intercepted before production"); assert(posts.filter(x=>x.kind==="quarantine").length===0,"no initialization or unknown POST escaped the explicit contract");
      assert(posts.length===9,"no extra known view/signals POST is allowed"); assert(JSON.stringify(trace)===JSON.stringify([{route:"view",revision:0,response:1,visible:["E2E Tone"]},{route:"view",revision:1,response:2,visible:["E2E Tone","E2E Chirp"]},{route:"batch",revision:2,status:422},{route:"batch",revision:2,status:409},{route:"batch",revision:2,status:200,response:3},{route:"conflict",revision:3,status:409},{route:"duplicate",revision:3,response:4},{route:"extract_time_limits",revision:4,response:5},{route:"delete",revision:5,response:6}]),"immutable Signals request/response trace must exactly match the frozen contract");
    });
  } finally {
    for (const pair of [["**/api/signals*",signalsRoute],["**/api/view*",viewRoute],["**/api/workspace/variables*",catalogRoute],["**/api/state*",stateRoute]]) if(pair[1]) await page.unroute(pair[0],pair[1]);
    if(quarantine){try{await page.reload({waitUntil:"domcontentloaded"});await origin(page,config,assert,"cleanup target");await ready(page,config);}finally{await page.unroute("**/api/**",quarantine);}}
  }
}
testSignalsInspectorActions.requiredFeatures=["frontend-state-management","graph-output-zone","signal-analyser-displays","inspector-ui","signal-inventory-actions"];
module.exports=testSignalsInspectorActions;
