"use strict";

const { openAppPage, testIdSelector } = require("../../support/app_page");
const { endpointMatches, performanceLog, responseJson, signalRowsState, waitForApi, waitForSettled } = require("../../support/signal_analyser_page");
const TIMEOUT = 30000;
const DEFAULT = { overlap_percent: 50, leakage: 0.5, frequency_limits: null, frequency_scale: "linear", power_limits: null };
function id(page, config, key) { return page.locator(testIdSelector(config.app.testIds[key])); }
function same(a, b) { return JSON.stringify(a || null) === JSON.stringify(b || null); }
function active(s) { return (s.displays || []).find(function (d) { return d.id === s.active_display_id; }); }
function settings(s) { return s.spectrogram_settings; }
function source(s) { const d = active(s); return d && d.analysis_signal || ""; }
async function state(page) { return page.evaluate(function () { return window.SignalAnalyserApi.getState(); }); }
function payload(s) { return s.plot_payload && s.plot_payload.spectrogram || s.plots && s.plots.spectrogram; }
function powerMeta(s) { return payload(s) && payload(s).power_limits; }
function signature(s) { const p = payload(s) || {}; return { x: JSON.stringify(p.x || []), y: JSON.stringify(p.y || []), z: JSON.stringify(p.z || []) }; }
function exact(assert, s, expected, label) { const d = active(s), value = settings(s); assert(d && same(value, d.spectrogram_settings) && same(value, expected) && Object.keys(value || {}).sort().join(",") === "frequency_limits,frequency_scale,leakage,overlap_percent,power_limits", `${label}: exact five-key Spectrogram settings required`); }
function body(r) { return JSON.parse(r.postData() || "{}"); }
async function mutation(page, config, action, log, label, expected, status) {
  const before = (await state(page)).state_revision, requests = [], started = Date.now(); status = status || 200;
  const on = function (r) { if (endpointMatches({ request: function () { return r; }, url: function () { return r.url(); } }, config.app.api.view, "POST")) requests.push(r); };
  page.on("request", on);
  try { const responsePromise = waitForApi(page, config, config.app.api.view, "POST"); await action(); const response = await responsePromise, result = await responseJson(response, label); performanceLog(log, label, Date.now() - started, undefined, `HTTP ${response.status()}; ${requests.length} request(s)`); const sent = body(requests[0] || { postData: function () { return "{}"; } }); assertRequest(response.status() === status && requests.length === 1 && (!expected || same(sent.spectrogram_settings, expected) && Object.keys(sent.spectrogram_settings || {}).length === 5), `${label}: expected one exact five-key request`); if (status === 200) assertRequest(result.state_revision === before + 1, `${label}: revision must increment once`); await waitForSettled(page, config); return result; } finally { page.off("request", on); }
}
function assertRequest(ok, message) { if (!ok) throw new Error(message); }
async function plot(page, config, value, log, label) { if (await id(page, config, "plotTypeSelect").inputValue() !== value) await mutation(page, config, function () { return id(page, config, "plotTypeSelect").selectOption(value); }, log, label); }
async function selectDisplay(page, config, displayId, log, label) { if ((await state(page)).active_display_id === displayId) return; const started = Date.now(), response = waitForApi(page, config, config.app.api.displays, "POST"); await page.locator(testIdSelector(`display-tab-${displayId}`)).click(); const result = await response; if (!result.ok()) throw new Error(`${label}: display selection failed`); await waitForSettled(page, config); performanceLog(log, label, Date.now() - started, undefined, `HTTP ${result.status()}`); }
async function selectSource(page, config, name, log, label) { if (source(await state(page)) === name) return; const row = (await signalRowsState(page, config)).find(function (r) { return r.name === name; }); if (!row) throw new Error(`${label}: source row unavailable`); await mutation(page, config, function () { return page.locator(testIdSelector(row.id)).click(); }, log, label); }
async function pair(page, config, min, max, log, label, expected, status) { await id(page, config, "spectrogramPowerMinInput").fill(String(min)); await id(page, config, "spectrogramPowerMaxInput").fill(String(max)); return mutation(page, config, function () { return id(page, config, "spectrogramPowerMaxInput").press("Enter"); }, log, label, expected, status); }
async function noRequest(page, config, action, assert, log, label) { const revision = (await state(page)).state_revision, requests = [], started = Date.now(), on = function (r) { if (endpointMatches({ request: function () { return r; }, url: function () { return r.url(); } }, config.app.api.view, "POST")) requests.push(r); }; page.on("request", on); try { await action(); await page.waitForFunction(function (a) { return Number(document.querySelector(a.selector).getAttribute("data-state-revision")) === a.revision || !document.querySelector(a.error).hidden; }, { selector: testIdSelector(config.app.testIds.shell), error: testIdSelector(config.app.testIds.spectrogramPowerLimitsError), revision: revision }, { timeout: TIMEOUT }); assert(requests.length === 0 && (await state(page)).state_revision === revision, `${label}: local edit must make zero requests`); performanceLog(log, label, Date.now() - started, undefined, "zero /api/view; revision unchanged"); return powerUi(page, config); } finally { page.off("request", on); } }
async function rendered(page, config) { await page.waitForFunction(function (selector) { const h = document.querySelector(selector), t = h && (h.data || h._fullData || []).find(function (x) { return x.type === "heatmap"; }); return h && h.dataset.plotReady === "true" && t; }, testIdSelector(config.app.testIds.activePlotHost), { timeout: TIMEOUT }); return id(page, config, "activePlotHost").evaluate(function (h) { const t = (h.data || h._fullData || []).find(function (x) { return x.type === "heatmap"; }); return { zauto: t.zauto, zmin: t.zmin, zmax: t.zmax, x: JSON.stringify(t.x), y: JSON.stringify(t.y), z: JSON.stringify(t.z) }; }); }
async function powerUi(page, config) { return { min: await id(page, config, "spectrogramPowerMinInput").inputValue(), max: await id(page, config, "spectrogramPowerMaxInput").inputValue(), effective: (await id(page, config, "spectrogramPowerLimitsEffective").textContent()).trim(), error: (await id(page, config, "spectrogramPowerLimitsError").textContent()).trim(), errorVisible: await id(page, config, "spectrogramPowerLimitsError").isVisible() }; }
async function restoreMembership(page, config, names, log) { for (const row of await signalRowsState(page, config)) { const wanted = names.indexOf(row.name) >= 0; if (Boolean(row.checked) !== wanted) await mutation(page, config, function () { return page.locator(testIdSelector(row.checkboxTestId)).setChecked(wanted); }, log, `cleanup membership ${row.name}`); } }
async function restoreRow(page, config, name, log) { if (!name || (await state(page)).row_selected_signal === name) return; const row = (await signalRowsState(page, config)).find(function (r) { return r.name === name; }); if (!row) throw new Error("cleanup row selection unavailable"); await mutation(page, config, function () { return page.locator(testIdSelector(row.id)).click(); }, log, "cleanup row selection"); }

async function testSpectrogramPowerLimits({ appUrl, assert, config, log, page, step, useCurrentPage }) {
  const original = { created: "" };
  try {
    await step("Auto and Manual power limits are atomic and change only Plotly color range", async function () {
      log("browser_workspace_setup: background CDP only; no focus/Space/window action; no MATLAB coordination needed; MATLAB unchanged"); await openAppPage(page, { appUrl, config, log, useCurrentPage }); const opened = await state(page); Object.assign(original, { active: opened.active_display_id, count: (opened.displays || []).length, plot: await id(page, config, "plotTypeSelect").inputValue(), settings: settings(opened), source: source(opened), row: opened.row_selected_signal, spectrum: opened.spectrum_settings, membership: (await signalRowsState(page, config)).filter(function (r) { return r.checked; }).map(function (r) { return r.name; }) }); await plot(page, config, "spectrogram", log, "open Spectrogram"); const auto = await state(page); exact(assert, auto, DEFAULT, "Auto"); assert(await id(page, config, "spectrogramPowerLimitsControls").isVisible(), "Power controls must be visible in Spectrogram settings"); const before = signature(auto), autoRender = await rendered(page, config), autoPower = payload(auto).power_limits && payload(auto).power_limits.effective; assert(autoRender.zauto === true || autoPower && autoPower.min_db === autoPower.max_db, "Auto must render Plotly zauto unless a deterministic constant range needs fallback"); if (autoPower && autoPower.min_db === autoPower.max_db) assert(autoRender.zauto === false && autoRender.zmin === autoPower.min_db - 1 && autoRender.zmax === autoPower.max_db + 1, "constant deterministic fixture must use renderer-only ±1 power fallback"); const manual = { min_db: -100, max_db: -20, units: "dB" }, wanted = Object.assign({}, DEFAULT, { power_limits: manual }); const changed = await pair(page, config, -100, -20, log, "set Manual power range", wanted); exact(assert, changed, wanted, "Manual"); assert(same(signature(changed), before), "Manual power range must preserve backend x/y/z"); const m = await rendered(page, config); assert(m.zauto === false && m.zmin === -100 && m.zmax === -20 && m.x === before.x && m.y === before.y && m.z === before.z, "Manual must set Plotly zauto/zmin/zmax without changing x/y/z"); const reset = await pair(page, config, "", "", log, "set Auto power range", DEFAULT), resetPower = payload(reset).power_limits && payload(reset).power_limits.effective, resetRender = await rendered(page, config); exact(assert, reset, DEFAULT, "Auto reset"); assert(resetRender.zauto === true || resetPower && resetPower.min_db === resetPower.max_db, "Auto reset must restore zauto unless the deterministic constant fallback applies"); original.manual = manual;
    });
    await step("local incomplete/equal/reversed, 422 and bounded second-409 preserve accepted intent", async function () {
      const wanted = Object.assign({}, DEFAULT, { power_limits: original.manual }); await pair(page, config, -100, -20, log, "restore Manual", wanted); const incomplete = await noRequest(page, config, async function () { await id(page, config, "spectrogramPowerMinInput").fill("-100"); await id(page, config, "spectrogramPowerMaxInput").fill(""); await id(page, config, "spectrogramPowerMaxInput").press("Enter"); }, assert, log, "incomplete power range"); assert(incomplete.errorVisible && incomplete.min === "-100" && incomplete.max === "-20", "incomplete range must show local error and restore accepted pair"); await noRequest(page, config, async function () { await id(page, config, "spectrogramPowerMinInput").fill("-100"); await id(page, config, "spectrogramPowerMaxInput").fill("-20"); await id(page, config, "spectrogramPowerMaxInput").press("Enter"); }, assert, log, "equal canonical power no-op"); const equalInvalid = await noRequest(page, config, async function () { await id(page, config, "spectrogramPowerMinInput").fill("-50"); await id(page, config, "spectrogramPowerMaxInput").fill("-50"); await id(page, config, "spectrogramPowerMaxInput").press("Enter"); }, assert, log, "equal invalid power range"); assert(equalInvalid.errorVisible && equalInvalid.min === "-100" && equalInvalid.max === "-20", "equal range must show local error and restore accepted pair"); const reversed = await noRequest(page, config, async function () { await id(page, config, "spectrogramPowerMinInput").fill("-20"); await id(page, config, "spectrogramPowerMaxInput").fill("-100"); await id(page, config, "spectrogramPowerMaxInput").press("Enter"); }, assert, log, "reversed power range"); assert(reversed.errorVisible && reversed.min === "-100" && reversed.max === "-20", "reversed range must show local error and restore accepted pair");
      const rejected = Object.assign({}, DEFAULT, { power_limits: { min_db: -90, max_db: -30, units: "dB" } }); let saw422 = false; await page.route("**/api/view*", async function (route) { if (!saw422 && route.request().method() === "POST") { saw422 = true; await route.fulfill({ status: 422, contentType: "application/json", body: JSON.stringify({ ok: false, error: { message: "synthetic power rejection" } }) }); return; } await route.continue(); }); try { await pair(page, config, -90, -30, log, "synthetic power 422", rejected, 422); } finally { await page.unroute("**/api/view*"); } const after422 = await state(page), ui422 = await powerUi(page, config), meta422 = powerMeta(after422); assert(saw422 && same(settings(after422), wanted) && same(meta422, { mode: "explicit", requested: original.manual, effective: original.manual }) && ui422.min === "-100" && ui422.max === "-20" && ui422.effective === "Effective: -100…-20 dB" && ui422.errorVisible && ui422.error, "422 must restore accepted P-min/P-max/effective metadata and show error");
      let count409 = 0; const bodies = [], revision = (await state(page)).state_revision; await page.route("**/api/view*", async function (route) { if (route.request().method() === "POST") { bodies.push(body(route.request())); count409 += 1; if (count409 <= 2) { await route.fulfill({ status: 409, contentType: "application/json", body: JSON.stringify({ current: await state(page) }) }); return; } } await route.continue(); }); try { await id(page, config, "spectrogramPowerMinInput").fill("-90"); await id(page, config, "spectrogramPowerMaxInput").fill("-30"); await id(page, config, "spectrogramPowerMaxInput").press("Enter"); await page.waitForFunction(function (a) { const e = document.querySelector(a); return e && !e.hidden && e.textContent.trim(); }, testIdSelector(config.app.testIds.spectrogramPowerLimitsError), { timeout: TIMEOUT }); } finally { await page.unroute("**/api/view*"); } const after409 = await state(page), ui409 = await powerUi(page, config), meta409 = powerMeta(after409); assert(count409 === 2 && bodies.every(function (b) { return same(b.spectrogram_settings, rejected) && Object.keys(b.spectrogram_settings || {}).length === 5; }) && after409.state_revision === revision && same(meta409, { mode: "explicit", requested: original.manual, effective: original.manual }) && ui409.min === "-100" && ui409.max === "-20" && ui409.effective === "Effective: -100…-20 dB" && ui409.errorVisible && ui409.error, "second 409 must stop, restore accepted P-min/P-max/effective metadata and show error"); await pair(page, config, -100, -20, log, "restore accepted Manual", wanted);
    });
    await step("frequency-scale presentation changes independently of requested Manual power limits", async function () {
      const wanted = Object.assign({}, DEFAULT, { power_limits: original.manual }), before = await state(page), beforeSignature = signature(before), rawY = payload(before).y || [], positive = rawY.filter(function (v) { return v > 0; }), expectedY = rawY.map(function (v) { return v <= 0 ? Math.min.apply(null, positive) / 2 : v; }), logSettings = Object.assign({}, wanted, { frequency_scale: "log" }); assert(!await id(page, config, "spectrogramFrequencyScaleSelect").isDisabled() && positive.length, "C17 requires a real source with enabled Linear/Log control"); const logged = await mutation(page, config, function () { return id(page, config, "spectrogramFrequencyScaleSelect").selectOption("log"); }, log, "set Log with Manual power limits", logSettings); exact(assert, logged, logSettings, "Log preserves Manual power limits"); assert(same(signature(logged), beforeSignature) && same(powerMeta(logged), { mode: "explicit", requested: original.manual, effective: original.manual }), "Log must preserve backend x/y/z and Manual requested/effective power metadata"); const logRender = await rendered(page, config); assert(logRender.zauto === false && logRender.zmin === -100 && logRender.zmax === -20 && logRender.x === beforeSignature.x && logRender.z === beforeSignature.z && logRender.y === JSON.stringify(expectedY), "Log must change only rendered C16 y presentation while retaining Manual color range"); const linear = await mutation(page, config, function () { return id(page, config, "spectrogramFrequencyScaleSelect").selectOption("linear"); }, log, "restore Linear with Manual power limits", wanted); exact(assert, linear, wanted, "Linear restore preserves Manual power limits"); const linearRender = await rendered(page, config); assert(same(signature(linear), beforeSignature) && linearRender.y === JSON.stringify(rawY) && linearRender.zauto === false && linearRender.zmin === -100 && linearRender.zmax === -20, "Linear restore must restore rendered y only and retain Manual color range");
    });
    await step("A/B, Clear/re-add, source and Spectrum changes stay independent", async function () {
      const wanted = Object.assign({}, DEFAULT, { power_limits: original.manual }); await plot(page, config, "spectrum", log, "open independent Spectrum"); const spectrumBefore = (await state(page)).spectrum_settings; await plot(page, config, "spectrogram", log, "return Spectrogram"); exact(assert, await state(page), wanted, "Spectrum independence"); assert(same((await state(page)).spectrum_settings, spectrumBefore), "Spectrogram power controls must not change Spectrum"); const create = waitForApi(page, config, config.app.api.displays, "POST"); await id(page, config, "addDisplay").click(); if (!(await create).ok()) throw new Error("create Display B failed"); await waitForSettled(page, config); original.created = (await state(page)).active_display_id; await plot(page, config, "spectrogram", log, "open B Spectrogram"); exact(assert, await state(page), DEFAULT, "B default Auto"); await selectDisplay(page, config, original.active, log, "return A"); const cleared = await mutation(page, config, async function () { await id(page, config, "displayOverflowTrigger").click(); await id(page, config, "clearDisplayAction").click(); }, log, "clear A", wanted); exact(assert, cleared, wanted, "Clear preserves power intent"); assert(!source(cleared) && same(powerMeta(cleared), { mode: "explicit", requested: original.manual, effective: original.manual }) && await id(page, config, "spectrogramPowerMinInput").isDisabled() && await id(page, config, "spectrogramPowerMaxInput").isDisabled() && (await id(page, config, "spectrogramPowerLimitsEffective").textContent()).trim() === "Effective: -100…-20 dB", "no-source Clear must retain exact explicit requested/effective metadata while disabling controls"); const row = (await signalRowsState(page, config)).find(function (r) { return !r.checked && r.checkboxTestId; }); if (!row) throw new Error("Clear needs a re-addable signal"); const readded = await mutation(page, config, function () { return page.locator(testIdSelector(row.checkboxTestId)).setChecked(true); }, log, "re-add source", wanted); exact(assert, readded, wanted, "re-add preserves power intent"); assert(source(readded) && !await id(page, config, "spectrogramPowerMinInput").isDisabled(), "re-add must restore source and enabled controls"); const alternate = (readded.signals || []).find(function (s) { return active(readded).visible_signals.indexOf(s.name) >= 0 && s.name !== source(readded); }); if (alternate) { await selectSource(page, config, alternate.name, log, "switch source"); exact(assert, await state(page), wanted, "source change preserves power intent"); } else log("source independence skipped: no alternate visible source");
    });
  } finally {
    try { if (original.created) { await selectDisplay(page, config, original.created, log, "cleanup B"); const close = waitForApi(page, config, config.app.api.displays, "POST"); await page.locator(testIdSelector(`close-display-${original.created}`)).click(); if (!(await close).ok()) throw new Error("cleanup B close failed"); await waitForSettled(page, config); } if (original.active) { await selectDisplay(page, config, original.active, log, "cleanup A"); await restoreMembership(page, config, original.membership, log); await selectSource(page, config, original.source, log, "cleanup source"); const current = await state(page); if (!same(settings(current), original.settings)) { await plot(page, config, "spectrogram", log, "cleanup Spectrogram"); const p = original.settings.power_limits; await pair(page, config, p ? p.min_db : "", p ? p.max_db : "", log, "cleanup power intent", original.settings); } await restoreRow(page, config, original.row, log); await plot(page, config, original.plot, log, "cleanup plot"); const final = await state(page), members = (await signalRowsState(page, config)).filter(function (r) { return r.checked; }).map(function (r) { return r.name; }); assert(final.active_display_id === original.active && (final.displays || []).length === original.count && same(members, original.membership) && source(final) === original.source && final.row_selected_signal === original.row && same(settings(final), original.settings) && same(final.spectrum_settings, original.spectrum) && await id(page, config, "plotTypeSelect").inputValue() === original.plot, "cleanup must restore active/count/membership/source/row/settings/plot/Spectrum"); } } catch (error) { log(`cleanup Spectrogram Power Limits: ${error.message}`); throw error; }
  }
}
testSpectrogramPowerLimits.requiredFeatures = ["frontend-state-management", "signal-analyser-displays", "typed-spectrogram", "spectrogram-power-limits"];
module.exports = testSpectrogramPowerLimits;
