"use strict";

const { openAppPage, testIdSelector } = require("../../support/app_page");
const { endpointMatches, performanceLog, responseJson, signalRowsState, waitForApi, waitForSettled } = require("../../support/signal_analyser_page");
const TIMEOUT = 30000;
const DEFAULT = { overlap_percent: 50, leakage: 0.5, frequency_limits: null, frequency_scale: "linear" };
function id(page, config, name) { return page.locator(testIdSelector(config.app.testIds[name])); }
function shell(page, config) { return id(page, config, "shell"); }
function same(a, b) { return JSON.stringify(a || null) === JSON.stringify(b || null); }
function active(s) { return (s.displays || []).find(function (d) { return d.id === s.active_display_id; }); }
function source(s) { const d = active(s); return d && d.analysis_signal || ""; }
function meta(s) { const p = s.plots && s.plots.spectrogram || s.plot_payload && s.plot_payload.spectrogram; return p && p.frequency_scale; }
async function state(page) { return page.evaluate(function () { return window.SignalAnalyserApi.getState(); }); }
function settings(s) { return s.spectrogram_settings; }
function assertFour(assert, s, expected, label) { const d = active(s); assert(d && same(settings(s), d.spectrogram_settings) && same(settings(s), expected) && Object.keys(settings(s) || {}).sort().join(",") === "frequency_limits,frequency_scale,leakage,overlap_percent", `${label}: exact four-key Spectrogram settings required`); }
function sig(s) { const p = s.plot_payload && s.plot_payload.spectrogram || s.plots && s.plots.spectrogram; return { x: JSON.stringify(p && p.x), y: JSON.stringify(p && p.y), z: JSON.stringify(p && p.z) }; }
async function mutate(page, config, action, log, label, expected, status) {
  const before = Number(await shell(page, config).getAttribute("data-state-revision")), requests = []; status = status || 200;
  const on = function (r) { if (endpointMatches({ request: function () { return r; }, url: function () { return r.url(); } }, config.app.api.view, "POST")) requests.push(r); }; page.on("request", on); const started = Date.now();
  try { const responsePromise = waitForApi(page, config, config.app.api.view, "POST"); await action(); const response = await responsePromise, payload = await responseJson(response, label); performanceLog(log, label, Date.now() - started, undefined, `HTTP ${response.status()}; ${requests.length} request(s)`); const body = JSON.parse(requests[0] && requests[0].postData() || "{}"); if (response.status() !== status || requests.length !== 1 || (expected && (!same(body.spectrogram_settings, expected) || Object.keys(body.spectrogram_settings || {}).length !== 4))) throw new Error(`${label}: exact one full four-key /api/view request required`); if (status === 200 && payload.state_revision !== before + 1) throw new Error(`${label}: expected revision +1`); await waitForSettled(page, config); return payload; } finally { page.off("request", on); }
}
async function plot(page, config, value, log, label) { if (await id(page, config, "plotTypeSelect").inputValue() !== value) await mutate(page, config, function () { return id(page, config, "plotTypeSelect").selectOption(value); }, log, label, null); }
async function selectSource(page, config, name, log, label) { if (source(await state(page)) === name) return; const row = (await signalRowsState(page, config)).find(function (r) { return r.name === name; }); if (!row) throw new Error(`${label}: source absent`); await mutate(page, config, function () { return page.locator(testIdSelector(row.id)).click(); }, log, label, null); }
async function restoreRowSelection(page, config, name, log) { if (!name || (await state(page)).row_selected_signal === name) return; const row = (await signalRowsState(page, config)).find(function (r) { return r.name === name; }); if (!row) throw new Error(`cleanup row-selected signal ${name} is absent`); await mutate(page, config, function () { return page.locator(testIdSelector(row.id)).click(); }, log, "cleanup row-selected signal", null); }
async function selectDisplay(page, config, displayId, log, label) { if (await shell(page, config).getAttribute("data-active-display-id") === displayId) return; const responsePromise = waitForApi(page, config, config.app.api.displays, "POST"); await page.locator(testIdSelector(`display-tab-${displayId}`)).click(); const response = await responsePromise; if (!response.ok()) throw new Error(`${label}: display select failed`); await waitForSettled(page, config); }
async function testSpectrogramFrequencyScale({ appUrl, assert, config, log, page, step, useCurrentPage }) {
  const original = {};
  try {
    await step("real requested/effective Linear then Log preserves backend arrays", async function () {
      log("browser_workspace_setup: planned background CDP only; no focus/Space/window action; MATLAB unchanged"); await openAppPage(page, { appUrl, config, log, useCurrentPage }); const opened = await state(page); original.active = opened.active_display_id; original.displayCount = (opened.displays || []).length; original.plot = await id(page, config, "plotTypeSelect").inputValue(); original.settings = settings(opened); original.source = source(opened); original.rowSelected = opened.row_selected_signal; original.membership = (await signalRowsState(page, config)).filter(function (r) { return r.checked; }).map(function (r) { return r.name; }); await plot(page, config, "spectrogram", log, "open Spectrogram"); const linear = await state(page); assertFour(assert, linear, DEFAULT, "default Linear"); assert(same(meta(linear), { requested: "linear", effective: "linear", available: ["linear", "log"] }), "real source must publish Linear requested/effective/available metadata"); assert(await id(page, config, "spectrogramFrequencyScaleSelect").inputValue() === "linear" && !await id(page, config, "spectrogramFrequencyScaleSelect").isDisabled(), "real frequency-scale select must offer Linear/Log"); const before = sig(linear), expected = Object.assign({}, DEFAULT, { frequency_scale: "log" }); const logState = await mutate(page, config, function () { return id(page, config, "spectrogramFrequencyScaleSelect").selectOption("log"); }, log, "request Spectrogram Log", expected); assertFour(assert, logState, expected, "requested Log"); assert(same(sig(logState), before), "backend x/y/z must remain unchanged for presentation-only Log"); await page.waitForFunction(function (selector) { const h = document.querySelector(selector); return h && h.getAttribute("data-plot-ready") === "true" && h._fullLayout && h._fullLayout.yaxis.type === "log"; }, testIdSelector(config.app.testIds.activePlotHost), { timeout: TIMEOUT }); const rendered = await id(page, config, "activePlotHost").evaluate(function (host) { const t = host && (host.data || host._fullData || []).find(function (trace) { return trace.type === "heatmap"; }); return { type: host && host._fullLayout && host._fullLayout.yaxis && host._fullLayout.yaxis.type, y: t && Array.from(t.y || []), z: t && t.z }; }); const backendY = (logState.plot_payload && logState.plot_payload.spectrogram || logState.plots.spectrogram).y; const positive = backendY.filter(function (v) { return v > 0; }); assert(rendered.type === "log" && rendered.y.length === backendY.length && rendered.y[0] === Math.min.apply(null, positive) / 2 && rendered.y.slice(1).every(function (v, i) { return v === backendY.slice(1)[i]; }) && JSON.stringify(rendered.z) === JSON.stringify((logState.plot_payload && logState.plot_payload.spectrogram || logState.plots.spectrogram).z), "Plotly Log must replace only zero with minPositive/2 and preserve positive bins/z rows"); original.logSettings = expected;
    });
    await step("conditional complex keeps requested Log and source return restores effective Log", async function () {
      const snapshot = await state(page), complex = (snapshot.signals || []).find(function (s) { return /complex|комплекс/i.test(String(s.data_type || "")) && active(snapshot).visible_signals.indexOf(s.name) >= 0; }); if (!complex) { log("complex scale path skipped: no visible complex source"); return; } await selectSource(page, config, complex.name, log, "select complex source"); const locked = await state(page); assertFour(assert, locked, original.logSettings, "complex preserves requested Log"); assert(same(meta(locked), { requested: "log", effective: "linear", available: ["linear"] }) && await id(page, config, "spectrogramFrequencyScaleSelect").isDisabled(), "complex must retain requested Log but lock effective Linear"); await selectSource(page, config, original.source, log, "return real source"); const restored = await state(page); assert(same(meta(restored), { requested: "log", effective: "log", available: ["linear", "log"] }), "real return must restore effective Log without frontend writeback");
    });
    await step("422, bounded 409, Spectrum isolation and Display lifecycle", async function () {
      if (source(await state(page)) !== original.source) await selectSource(page, config, original.source, log, "restore real source");
      const wanted = original.logSettings || Object.assign({}, DEFAULT, { frequency_scale: "log" });
      const before422 = await state(page); let rejected = false;
      await page.route("**/api/view*", async function (route) { if (!rejected && route.request().method() === "POST") { rejected = true; await route.fulfill({ status: 422, contentType: "application/json", body: JSON.stringify({ ok: false, error: { message: "synthetic scale rejection" } }) }); return; } await route.continue(); });
      try { await mutate(page, config, function () { return id(page, config, "spectrogramFrequencyScaleSelect").selectOption("linear"); }, log, "synthetic scale 422", DEFAULT, 422); } finally { await page.unroute("**/api/view*"); }
      await page.waitForFunction(function (ids) { const select = document.querySelector(ids.select), effective = document.querySelector(ids.effective), error = document.querySelector(ids.error); return select && select.value === "log" && effective && effective.textContent.trim().toLowerCase() === "log" && error && !error.hidden && error.textContent.trim(); }, { select: testIdSelector(config.app.testIds.spectrogramFrequencyScaleSelect), effective: testIdSelector(config.app.testIds.spectrogramFrequencyScaleEffective), error: testIdSelector(config.app.testIds.spectrogramFrequencyScaleError) }, { timeout: TIMEOUT }); assert(rejected && same(settings(await state(page)), settings(before422)), "422 must roll back accepted four-key settings");
      const revision = (await state(page)).state_revision, bodies = []; let count409 = 0;
      await page.route("**/api/view*", async function (route) { if (route.request().method() === "POST") { bodies.push(JSON.parse(route.request().postData() || "{}")); count409 += 1; if (count409 <= 2) { await route.fulfill({ status: 409, contentType: "application/json", body: JSON.stringify({ current: await state(page) }) }); return; } } await route.continue(); });
      try { await id(page, config, "spectrogramFrequencyScaleSelect").selectOption("linear"); await page.waitForFunction(function (ids) { const select = document.querySelector(ids.select), effective = document.querySelector(ids.effective), error = document.querySelector(ids.error); return select && select.value === "log" && effective && effective.textContent.trim().toLowerCase() === "log" && error && !error.hidden && error.textContent.trim(); }, { select: testIdSelector(config.app.testIds.spectrogramFrequencyScaleSelect), effective: testIdSelector(config.app.testIds.spectrogramFrequencyScaleEffective), error: testIdSelector(config.app.testIds.spectrogramFrequencyScaleError) }, { timeout: TIMEOUT }); } finally { await page.unroute("**/api/view*"); }
      assert(count409 === 2 && bodies.length === 2 && bodies.every(function (b) { return same(b.spectrogram_settings, DEFAULT) && Object.keys(b.spectrogram_settings || {}).length === 4; }) && Number(await shell(page, config).getAttribute("data-state-revision")) === revision, "first 409 may replay once; second 409 must stop without revision change");
      await selectSource(page, config, original.source, log, "restore source after 409");
      await plot(page, config, "spectrum", log, "open independent Spectrum"); const spectrumBefore = await state(page); await plot(page, config, "spectrogram", log, "return Spectrogram after Spectrum"); const afterSpectrum = await state(page); assert(same(afterSpectrum.spectrum_settings, spectrumBefore.spectrum_settings), "Spectrogram Frequency Scale must not change Spectrum settings");
      const create = waitForApi(page, config, config.app.api.displays, "POST"); await id(page, config, "addDisplay").click(); if (!(await create).ok()) throw new Error("create Display B failed"); await waitForSettled(page, config); original.created = await shell(page, config).getAttribute("data-active-display-id"); const b = await state(page); assertFour(assert, b, DEFAULT, "new Display B default"); await selectDisplay(page, config, original.active, log, "return A");
      const cleared = await mutate(page, config, async function () { await id(page, config, "displayOverflowTrigger").click(); await id(page, config, "clearDisplayAction").click(); }, log, "clear requested scale", wanted); assertFour(assert, cleared, wanted, "Clear retains requested scale"); assert(same(meta(cleared), { requested: "log", effective: null, available: [] }) && await id(page, config, "spectrogramFrequencyScaleSelect").inputValue() === "log" && await id(page, config, "spectrogramFrequencyScaleSelect").isDisabled() && (await id(page, config, "spectrogramFrequencyScaleEffective").textContent()).trim() === "", "Clear must retain requested Log with disabled select and blank effective metadata"); const row = (await signalRowsState(page, config)).find(function (r) { return !r.checked && r.checkboxTestId; }); if (!row) throw new Error("Clear requires re-addable signal"); const readded = await mutate(page, config, function () { return page.locator(testIdSelector(row.checkboxTestId)).setChecked(true); }, log, "re-add scale source", null); assertFour(assert, readded, wanted, "re-add retains requested scale"); assert(meta(readded).effective === "log", "re-add real source restores effective Log");
    });
  } finally { if (original.created) { await selectDisplay(page, config, original.created, log, "cleanup select B"); const close = waitForApi(page, config, config.app.api.displays, "POST"); await page.locator(testIdSelector(`close-display-${original.created}`)).click(); if (!(await close).ok()) throw new Error("cleanup close B failed"); await waitForSettled(page, config); } if (original.active) { await selectDisplay(page, config, original.active, log, "cleanup return A"); for (const row of await signalRowsState(page, config)) { const wanted = original.membership.indexOf(row.name) >= 0; if (Boolean(row.checked) !== wanted) await mutate(page, config, function () { return page.locator(testIdSelector(row.checkboxTestId)).setChecked(wanted); }, log, `cleanup membership ${row.name}`, null); } await selectSource(page, config, original.source, log, "cleanup source"); await restoreRowSelection(page, config, original.rowSelected, log); await plot(page, config, "spectrogram", log, "activate Spectrogram cleanup control"); const current = await state(page); if (original.settings && !same(settings(current), original.settings)) await mutate(page, config, function () { return id(page, config, "spectrogramFrequencyScaleSelect").selectOption(original.settings.frequency_scale); }, log, "cleanup frequency scale", original.settings); await plot(page, config, original.plot, log, "cleanup plot"); const final = await state(page), finalMembers = (await signalRowsState(page, config)).filter(function (row) { return row.checked; }).map(function (row) { return row.name; }); assert(final.active_display_id === original.active && (final.displays || []).length === original.displayCount && same(finalMembers, original.membership) && source(final) === original.source && final.row_selected_signal === original.rowSelected && same(settings(final), original.settings) && await id(page, config, "plotTypeSelect").inputValue() === original.plot, "cleanup must restore exact original active Display/count/membership/source/row selection/Spectrogram settings/plot"); } }
}
testSpectrogramFrequencyScale.requiredFeatures = ["frontend-state-management", "signal-analyser-displays", "typed-spectrogram", "spectrogram-frequency-limits", "spectrogram-frequency-scale"];
module.exports = testSpectrogramFrequencyScale;
